### ISSUE TITLE
番組検索で録画タイトルのキーワードがfullTitleにヒットしない

### ISSUE THREAD

**Issue by taikoyaP** [kanreisa/Chinachu#122]
某CSアニメチャンネルですが、一挙放送のタイトルのフォーマットが
[一挙]「ぽてまよ」全12話一挙放送
のようになっているので、「ぽてまよ」で検索してもヒットしません。
このあたりどうにかならないでしょうか。

**Comment by kanreisa** [comment]
修正しましたー
