### ISSUE TITLE
EPG from BS channels have a ~3 day gap in my EPG/Bangumi-view

### ISSUE THREAD

**Issue by viddypiddy** [kanreisa/Chinachu#123]
Hello, thanks for the great job with chinachu!
Sorry again for reporting in English, but my japanese power level is not strong enough ;-)

I have a problem which i can't seem to figure out.
My EPG gets a strange 3 day gap on BS channels for me. And I can't seem to figure out why!
Here is an example on BS-TBS, this is the case for almost every BS channel for me.
![chinachu-epg](https://cloud.githubusercontent.com/assets/1098530/5603497/c7fdfbc4-9387-11e4-8581-16debbe385a5.png)

I have tried recording my own file, and then run the chinachu-built epgdump on it like this
```
recpt1 --device /dev/pt3video0 --sid epg 151 - epg.ts
/home/chinachu/chinachu/usr/bin/epgdump /BS epg.ts epg.xml
```
In the epg.xml i can find shows for this channel during this time frame. But they don't show up in chinachu, and are not located in "schedule.json". I confirmed this by searching for the show title from the XML in the json-file.

```
$ grep -Ri "省エネの達人「企業編」" epg.xml
    <title lang="ja_JP">省エネの達人「企業編」</title>
$ grep -c "省エネの達人「企業編」" chinachu/data/schedule.json
0
```

Any idea what might be causing this?

Thank you!

**Comment by kanreisa** [comment]
happy new year.

Maybe that's not problem.
It just seems partially. EPG.
because BS/CS channel's EPG is large and it needs long recording time.

In default, EPG recording time is 60 seconds.
You can configure this on `config.json` like below:

```
"schedulerEpgRecordTime": 120
```

If not resolved, that is just blank schedule.

**Comment by viddypiddy** [comment]
Happy new year! Thank you for the response.
Often there is a easy solution, so that's what I was hoping for!
The reason I was confused is that it was in the middle of the EPG for 3 whole days.

I tried 120 seconds, and the gaps have gotten smaller. But still shows are missing from e.g WOWOW prime. Is really even more than 120 seconds needed then?

Example:
![chinachu-epg-2](https://cloud.githubusercontent.com/assets/1098530/5603629/242a687c-938f-11e4-8ec7-1eea56c852c9.png)

Rocky 2 is missing. From WOWOWs TV guide.
![wowow-epg](https://cloud.githubusercontent.com/assets/1098530/5603631/2ecf5580-938f-11e4-9d50-51ac0eac1281.png)

**Comment by kanreisa** [comment]
yes, maybe if needed.

**Comment by viddypiddy** [comment]
OK. Thank you, i will keep trying with different times.
Maybe there should be a higher default?
I guess this will be solved in Usushio anyway, with the continuous EPG upgrading :+1: 

Thanks alot! Looking forward to the release of Usushio!

**Comment by kanreisa** [comment]
yes, cool solutions has in Usushio.

thank you for using!
