### ISSUE TITLE
半角スペースを含むキーワードで検索できない・ルールでヒットしない

### ISSUE THREAD

**Issue by kazuki** [kanreisa/Chinachu#124]
半角スペースを含むキーワードで検索を行うと
URIのクエリ文字列には"title=a+b+c"となり，検索結果が期待したものとなりません．
手動でURIを書き換えて"title=a%20b%20c"とすると，期待した検索結果が得られます．

ただ，ルールのキーワードに半角スペースを含む文字列を指定した場合は，問題なく動作するようです．

**Comment by kazuki** [comment]
同様にスラッシュを含むキーワードも上手く行きません

**Comment by kanreisa** [comment]
修正しました。ご確認ください～

**Comment by kazuki** [comment]
半角スペースを含むタイトルの検索は出来るようになりました．ありがとうございます．

エスケープの問題かと思って半角スペースとだけ書きましたが，スラッシュを含む場合も上手く動作しないようです．ただスラッシュを含む場合はルールでもヒットしないので，別な問題かもしれません．

**Comment by kanreisa** [comment]
![](https://yabumi.cc/14aba79437b6dbb39ba4adea.png)

動くっぽい

**Comment by kazuki** [comment]
どうやらFirefox(stable, beta, aurora)では動作しないようです．
Chromium(41.0.2251.0)なら問題ありませんでした．

ちなみにFirefoxでニキータで検索すると無限リロードに陥ります...

**Comment by kanreisa** [comment]
!?

https://developer.mozilla.org/ja/docs/Web/API/window.location
> URL の hash の部分が、エンコードされた文字 （Core_JavaScript_1.5_Reference:Global_Functions:encodeURIComponent を参照）を含む場合、hash  は、デコードされた URL の部分を返します。これは、Firefox における、バグです。href、search、pathname  は、正しい、エンコードされた URL の部分を返します。 例:

**Comment by kanreisa** [comment]
再度修正しましたのでご確認くださぃ

**Comment by kazuki** [comment]
治っていることを確認しました．ありがとうございました．
