### ISSUE TITLE
ストリーミング再生の設定を保持する

### ISSUE THREAD

**Issue by ghost** [kanreisa/Chinachu#125]
要望になります．

現状のストリーミング再生の設定は常にデフォルト値で表示されますが，
前回の設定を引き継ぐことは出来ないでしょうか？
または，デフォルト値の変更．

ご検討をお願い致します．

**Comment by miyukki** [comment]
I think so too.

**Comment by simplelife0530** [comment]
ストリーミング再生に関して、追加で要望があります。
現状の設定では、再生時に画面上で右クリックで、「コントロールを表示」のメニューがでます。
「コントロールの表示」によって、再生位置の指定やフルスクリーン表示が可能となります。
できれば、最初から、「コントロールの表示」が出ている方が、使い勝手が良いと思います。
Anime Locker 4.0では、最初から「コントロールの表示」が出ている設定となっています。
