### ISSUE TITLE
EPG番組表の詳細情報を取得できるようにしてほしい

### ISSUE THREAD

**Issue by toytoytoy20** [kanreisa/Chinachu#130]
Win環境ではEDCB,TVROC、LinuxではRec10がEPGの詳細データの取得ができますがChinachuでも詳細情報が読み込めてキーワード検索できるようにしてほしいです。
用途としては出演者でキーワード検索することが多い為です。

取得に時間がかかるので賛否あると思いますがオプションで選択できたらいいなと思います。

**Comment by kanreisa** [comment]
既にそのように検索することが出来ます。

**Comment by upsilon** [comment]
「出演者」の検索とのことなので、おそらく拡張形式イベント記述子の事を指していると思います。

現行の epgdump では拡張形式イベント記述子をパースする処理は存在するものの、出力には使われていないようです。epgdump の出力に現れない以上 Chinachu で検索することはできません。
https://github.com/stz2012/epgdump/blob/4e4da34e76f881182e956eac7d843581435b5a39/eit.c#L420

**Comment by upsilon** [comment]
Rec10 で取得できるとのことであれば、Rec10 に同梱されている epgdump に置き換えれば取得できる可能性はあります（試してませんが）。
ただしソースを見る限りでは拡張形式イベント記述子の項目は `longdesc` 要素に含まれているため、Chinachu 側もこれを読み込み検索できるように手を加える必要があります。
https://bitbucket.org/gn64/rec10/src/32fccb888827247ca313b6d54800dcb3fedd7e4b/tstools/epgdump/epgdump.c?at=master#cl-270

**Comment by toytoytoy20** [comment]
upsilonさんのおっしゃる拡張形式イベント記述子というものだと思います。
Chinachuで取得できる詳細データは少ないので出演者が一部しか入っていないです。

需要が少ないんでしょうか？

Rec10のepgdumpに置き換えてChinachu側も手を加えて検索できるようにならないかと
思っていますがなかなか手がつけられずにいます。
データがjsonだと厳しいかもしれませんね。

**Comment by kanreisa** [comment]
次期バージョンで考えます。

**Comment by kanreisa** [comment]
Mirakurun 1.7.0 で拡張形式イベントに対応しました。 Air で実装確定です。
