### ISSUE TITLE
Node.jsのモジュール(http-auth、socket.io)がインストールに失敗してしまいます。

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#131]
Chinachuを最新版に更新後、
Node.jsのモジュール(http-auth、socket.io)がインストールに失敗してしまいます。
そのため、wuiが起動ない状態になります。

この前までは普通に動作していました。

手順
$ ./chinachu installer　→  5) Node.js Modulesを選択

what do you install? > 5
selected: Node.js Modules
Installing Node Modules using NPM...
npm WARN package.json opts@1.2.2 No repository field.
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/http-auth
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/http-auth
npm ERR! Error: ENOENT, open '/home/chinachu/chinachu/node_modules/socket.io/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.14.29-1vl7pae
npm ERR! command "/home/chinachu/chinachu/.nave/installed/0.10.26/bin/node" "/home/chinachu/chinachu/.nave/installed/0.10.26/bin/npm" "install"
npm ERR! cwd /home/chinachu/chinachu
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /home/chinachu/chinachu/node_modules/socket.io/package.json
npm ERR! code ENOENT
npm ERR! errno 34
・
・
・
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/chinachu/chinachu/npm-debug.log
npm ERR! not ok code 0
done.

**Comment by kanreisa** [comment]
多分アップデートは関係ないです。
```npm cache clean``` なければ ```.nave/npm cache clean```
を試してみてください。

**Comment by shirow-github** [comment]
.nave/npm cache cleanにて、インストールエラーは解消されました。
ありがとうございました。
