### ISSUE TITLE
Debian wheezyで環境構築中にエラー

### ISSUE THREAD

**Issue by yvb776** [kanreisa/Chinachu#132]
新規でAuto(full)を選択しインストールしていたところ、yasmのバージョンが1.2以上でないとダメだ、という旨のエラーが発生しました。（詳細覚えてないですごめんなさい、恐らくlibx264周り？）
Debian wheezyのリポジトリはyasm 1.1.0-1の為、wheezy-backportsより1.2.0-1~bpo70+1を導入したところ構築が完了しました。
ちなちゅのバグとは思いませんがご報告させていただきました。

**Comment by kanreisa** [comment]
libx264ですね。 既に解決されているようなのでクローズさせていただきます。
https://twitter.com/Chinachu_REC/status/557138994958311424
