### ISSUE TITLE
Chinachu最新版(node.js v0.12.0)に更新後、xspfで再生出来ません

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#135]
Chinachuを最新版にした所、node.jsのバージョンがv0.10.26からv0.12.0へ変更されました。
ですが、その後ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換)を行うと一向に再生が始まりません。
※VLCの「コーデック情報」を見ても何も表示されない。

./chinachu installerを実行した際、Node.js Modulesをインストールする過程でいくつか警告が表示されています。
'------------------------------------
npm WARN package.json opts@1.2.2 No repository field

npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load

npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,

npm WARN unmet dependency which is version 2.3.0

npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load

npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.5.0
'------------------------------------

とりあえず、chinachuの以下の部分を書き戻してv0.10.26を再インストールしたところ
Node.js Modulesをインストールする箇所で警告も出ず無事xspfで再生出来ました。

NODE_VER=0.12.0 → 0.10.26

**Comment by kanreisa** [comment]
すいません、再現しませんので、もう少し詳しく環境情報を書いてください。（アーキテクチャとか）

**Comment by kanreisa** [comment]
たまたま ビルドがコけていた可能性もありますので、再度 v0.12.0 のままインストーラー走らせてみてもらえますか？

**Comment by shirow-github** [comment]
環境は、以下のようになります。

OS:Vine Linux Seed x86 32bit PAE(kernel-3.14.29-1vl7pae)
CPU:Intel Core i5-4590S
M/B:MSI H87M-E35
Mem:4GB(2GB*2)
HDD1:Seagate ST3500418AS 500GB
HDD2:WDC WD30EFRX-68E 3TB
Tuner:EarthSoft PT3

それと、v0.12.0に戻して再インストールして試したところ「録画済み」の「M2TS」ファイルだけ再生不可のようです。

1) 番組表 → ライブ視聴 → ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換) → 再生可
2) 録画済み → 番組選択 → ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換) → 再生不可
3) 録画済み → 番組選択 → ストリーミング再生(WebM:映像VP8・音声Vorbis) → 再生可

ちなみに、「録画済み」の「M2TS」は映像(H.264、MPEG-2)、音声(AAC、Vorbis)のいずれを組み合わせても再生出来ませんでした。
※ライブ視聴の場合は、いずれのパターンでも再生可能です。(v0.10.26、v0.12.0共にOK)
※ちなみに、Node v0.10.26の場合の「録画済み」ファイルはいずれのパターンでも再生可能でした。

**Comment by miyukki** [comment]
最新版をfull installしましたが録画済みのXSPF(M2TS)でうまく再生されますね…

> ですが、その後ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換)を行うと一向に再生が始まりません。
> ※VLCの「コーデック情報」を見ても何も表示されない。
一向に再生が始まらないということはVLCはロードし続けてるという感じですか？

**Comment by kanreisa** [comment]
@shirow-github 
ログなどは何も出ていませんか？
なかなか再現できないので困ってますm(_ _)m

**Comment by shirow-github** [comment]
Chinachu側のログには、WUIログに「util.error: Use console.error instead
uncaughtException: Error: EINVAL, read」と出ています。

とりあえず、ブラウザやファイアーウォールも疑ったため以下を試してみました。

A)録画PC(chinachu最新版導入済み、Vine Seed)上での、録画済みの再生
環境：VLC(2.2.0-rc)、Chromium(37.0.2062.120 (281580))、Firefox(34.0.5)
Chromium→再生可
Firefox→再生可

VLCのログ(Debag出力)：ts info: MPEG-4 descriptor not found for pid 0x112 type 0xf
packetizer_mpeg4audio warning: ADTS CRC not supported

B)クライアントPC(Windows 7 SP1 x64)上での、録画済みの再生
環境：VLC(3.0.0-git)、Chrome(40.0.2214.111 m)、Sleipnir(4.4.0.4000:Blink40.0.2214.94)
ファイアーウォール：AVG Internet Security 2015.0.5646
Chrome→再生不可
Sleipnir→再生不可

VLCのログ(Debag出力)：何も表示されない

※ファイアーウォールのON/OFFを切り替えて試したのですが、いずれも再生不可でした。

次は新規インストールでの状況を試したいのですが、現環境をバックアップした後にコピーする
ファイルは以下でよろしいでしょうか？
config.json
rules.json
data/recorded.json
data/recording.json
data/reserves.json
data/schedule.json

**Comment by shirow-github** [comment]
あ、あと以下もコピー必要ですね
log/operator
log/scheduler
log/wui

**Comment by kanreisa** [comment]
./log/* はどのようにしても大丈夫です。
VLC 3.0 ですか、あとで試してみます。
TLSは使っていますか？

**Comment by shirow-github** [comment]
ちなみに、VLCは以下のARIB字幕対応版(WIn 32bit)を使用しています。
https://github.com/nkoriyama/vlc-aribsub/wiki

TLSは使用しておりません。
WUIログには以下のように表示されます。
**SELF-REGULATION WARNING**: If you want to access from outside of LAN, Please activate TLS.

また自宅内からのアクセスはPort20772で、パスワード無しで行っております。

**Comment by shirow-github** [comment]
新規にchinachuをインストールし、config.json等をバックアップからコピーして
録画済みを試してみたのですが再生不可でした。

config.jsonの設定が間違っているのでしょうか？
とりあえず、pastebinにあげてみました。
※Password等は、架空のものです。
http://pastebin.com/aSEHbFhX

**Comment by kanreisa** [comment]
設定は大丈夫なようです。

> B)クライアントPC(Windows 7 SP1 x64)上での、録画済みの再生

で再生できないという問題ですよね？
chrome://plugins ではどのように見えていますか？

**Comment by kanreisa** [comment]
なんでもないです。
Bのマシンで通常版のVLCを利用した場合どうなりますか？

**Comment by shirow-github** [comment]
B) クライアントPC(Windows 7 SP1 x64)にて、通常版のVLCを試してみました。

手順
1) VLC 3.0.0-git(win32 ARIB字幕対応版)を「設定とキャッシュ」を含めてアンインストール
2) VLC 2.1.5(win32通常版)をインストール
3) 録画済み → 番組選択 → ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換) → 再生可!!

2.1.5へ切り替えた所、無事に再生することが出来ました。
もしかして「設定とキャッシュ」を削除してアンインストールしたのが、結果良かったかもしれないので
2.1.5をアンインストールし、3.0.0-gitを再インストールして試してみました。

1) VLC 2.1.5(win32通常版)を「設定とキャッシュ」を含めてアンインストール
2) VLC 3.0.0-git(win32 ARIB字幕対応版)をインストール
3) 録画済み → 番組選択 → ストリーミング再生(XSPF:M2TSで映像・音声ともに無変換) → 再生可!!

結局、再インストールしたところ3.0.0-gitでも無事に再生することが出来ました。
VLCの設定やキャッシュにゴミがあって、それが悪さをしていたのかも知れません。

**Comment by shirow-github** [comment]
node.js v0.12.0での、VLCストリーミング再生はすることが出来たのですが、
VLCの「時間ツールバー」の経過時間と合計時間が0:00から変化しなくなってしまいました。

これは自分だけの環境の問題かと思うので、とりあえずご報告まで。
お手数お掛け致しました。

**Comment by kanreisa** [comment]
ありがとうございます。また何かあれば報告してください！
