### ISSUE TITLE
サスペンドで録画できなくなる。

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#136]
Ubuntuの電源の設定で、10分間待ってサスペンドの設定をしたところ、それ以降の録画が０MBのファイルとなり、録画ができなくなった。

電源を常に入れた状態で保持しなければならないのは、かなり負担が大きい。

**Comment by kanreisa** [comment]
録画コマンドがきちんと叩かれているかどうか確認してみてください。
録画コマンドが叩かれているのに動いていないのはChinachuにおける責任分界点を越えていますので、
カーネルモジュールやドライバ等をチェックしてください。

**Comment by simplelife0530** [comment]
確かに、Ubuntuの問題かもしれません。
今度CentOSに入れ換えて、検証してみます、
2015/02/15 0:44 "Yuki KAN" <notifications@github.com>:

**Comment by kanreisa** [comment]
ディストリの問題というより構成の問題の気がします。特に録画コマンドとドライバもいろいろありますので
ディストリを変えたところでまた同じ問題が発生する事もありえます。

サスペンド後にChinachuのプロセスが正しく動作しているか、録画コマンドを自分で叩いても問題がないか確認してみてください。

**Comment by simplelife0530** [comment]
了解しました。確認してまたお知らせします。
chinachu自体は動いています。録画予約は実行されています。ただし、録画ファイルのサイズが０MBになっているので、サスペンド後にrecpt1がきちんと動作していない可能性は高いです。

**Comment by simplelife0530** [comment]
recpt1コマンドやライブ視聴で確認したところ、特定のドライバが使えなくなっていました。何が原因かわかりませんが、ＰＴ２ドライバの問題でした。単にサスペンドやリブートで、ドライバが機能しなくなることは、想像できませんが、ドライバをインストールしなおす他ないようです。closeしてください。次は、CentOS７に入れ替えて、動作を確認してみます。Ubuntuはサーバーとして使うにはいろいろと不便なので。

**Comment by kanreisa** [comment]
@simplelife0530 Ubuntuを推奨した覚えは一度もないですが、Ubuntuを使うにしてもサーバー用のものがきちんとあります。
http://www.ubuntu.com/download/server

**Comment by kanreisa** [comment]
@simplelife0530 PT2 はかなりの不具合があるそうですので、まともに運用しようと思うのであればそれなりの覚悟が必要だと思います。

**Comment by simplelife0530** [comment]
Ubuntuは、私には使いにくいですね。CentOS7をインストールしてみたら、こちらの方が相性よさそうです。chinachuとは、関係ない話です。

**Comment by simplelife0530** [comment]
PT2は、windowsではとても安定しています。また、foltia anime lockerで半年運用していますが、トラブルはありません。たまたま私が運がいいだけかもしれません。今回は、PT2というハードではなく、ドライバかUbuntuの問題と考えています。

**Comment by kanreisa** [comment]
@simplelife0530 PT2持ってないので知りませんが、この辺も良く読んでください。

* https://github.com/kanreisa/Chinachu/wiki/Configuration#%E6%B3%A8%E6%84%8F
* http://baalzephon.no-ip.org/tech/index.php?Linux%2F%E3%83%86%E3%83%AC%E3%83%93%E9%96%A2%E9%80%A3%2FPT2

その辺の録画システムとは違ってChinachuはリアルタイムにコマンドを制御するのでドライバなどのバグを踏みやすいと思います。

**Comment by simplelife0530** [comment]
トラブルを読んでも、仕方ありません。PT3も4枚持っているので、PT3にします。PT2は、anime lockerで使います。

**Comment by simplelife0530** [comment]
今確認したら、Debian推奨なんですね。Ubuntuサーバーは、Debianベースだから、こちらの方がいいのかもしれません。しかし、CentOS7を使ってみましょう。

**Comment by kanreisa** [comment]
好きにしてください。
