### ISSUE TITLE
./chinachu updater すると色々エラー

### ISSUE THREAD

**Issue by falconws** [kanreisa/Chinachu#140]
Chinachuを更新しようと
$ ./chinachu updater
するとエラーが出ましたので、エラーログと共に報告します。

<pre>
Do you want to run chinachu installer (fast) [Y/n]? Y
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)		  5) Node.js Modules	   9) libfdk-aac
2) Auto (fast)		  6) epgdump		  10) libogg
3) submodule		  7) libx264		  11) libvorbis
4) Node.js Environment	  8) libvpx		  12) libav
what do you install? > selected: Auto (fast)
removed `/home/chinachu/chinachu/.nave'
Installing Node using Nave...
--2015-02-18 23:03:40--  https://github.com/isaacs/nave/archive/master.tar.gz
github.com (github.com) をDNSに問いあわせています... 192.30.252.131
github.com (github.com)|192.30.252.131|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/isaacs/nave/tar.gz/master [続く]
--2015-02-18 23:03:40--  https://codeload.github.com/isaacs/nave/tar.gz/master
codeload.github.com (codeload.github.com) をDNSに問いあわせています... 192.30.252.145
codeload.github.com (codeload.github.com)|192.30.252.145|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 7625 (7.4K) [application/x-gzip]
`STDOUT' に保存中

100%[======================================>] 7,625       --.-K/s   時間 0s    

2015-02-18 23:03:41 (28.9 MB/s) - stdout へ出力完了 [7625/7625]

nave-master/nave.sh
ディレクトリを削除しました: `/home/chinachu/chinachu/.nave/nave-master'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
installed from binary
`/home/chinachu/chinachu/.nave/node' -> `/home/chinachu/chinachu/.nave/installed/0.12.0/bin/node'
`/home/chinachu/chinachu/.nave/npm' -> `/home/chinachu/chinachu/.nave/installed/0.12.0/bin/npm'
done.
Installing Node Modules using NPM...
npm WARN package.json opts@1.2.2 No repository field.

> execsync@0.0.5 install /home/chinachu/chinachu/node_modules/execsync
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: ディレクトリ `/home/chinachu/chinachu/node_modules/execsync/build' に入ります
  CXX(target) Release/obj.target/shell/execsync.o
../execsync.cc:7:30: error: ‘Arguments’ does not name a type
 Handle<Value> execSync(const Arguments& args)
                              ^
../execsync.cc:7:41: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> execSync(const Arguments& args)
                                         ^
In file included from /home/chinachu/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../execsync.cc:3:
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> execSync(const int&)’:
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../execsync.cc:9:14: error: within this context
  HandleScope scope;
              ^
../execsync.cc:11:13: error: invalid types ‘const int[int]’ for array subscript
  if (!args[0]->IsString()) {
             ^
../execsync.cc:12:23: error: ‘New’ is not a member of ‘v8::String’
   Local<String> msg = String::New("Argument of 'execsync' must be String.");
                       ^
../execsync.cc:13:43: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(msg));
                                           ^
../execsync.cc:14:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Undefined());
                ^
../execsync.cc:14:32: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return scope.Close(Undefined());
                                ^
In file included from /home/chinachu/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../execsync.cc:3:
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../execsync.cc:17:45: error: invalid types ‘const int[int]’ for array subscript
  const String::Utf8Value utf8_command(args[0]);
                                             ^
../execsync.cc:22:23: error: ‘New’ is not a member of ‘v8::String’
   Local<String> msg = String::New("'popen' in 'execsync' failed.");
                       ^
../execsync.cc:23:43: error: ‘ThrowException’ was not declared in this scope
   ThrowException(Exception::TypeError(msg));
                                           ^
../execsync.cc:24:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Undefined());
                ^
../execsync.cc:24:32: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return scope.Close(Undefined());
                                ^
In file included from /home/chinachu/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../execsync.cc:3:
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../execsync.cc:36:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(String::New(result.c_str()));
               ^
../execsync.cc:36:21: error: ‘New’ is not a member of ‘v8::String’
  return scope.Close(String::New(result.c_str()));
                     ^
../execsync.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../execsync.cc:41:3: error: ‘NewSymbol’ is not a member of ‘v8::String’
   String::NewSymbol("execSync"),
   ^
../execsync.cc:42:33: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   FunctionTemplate::New(execSync)->GetFunction()
                                 ^
../execsync.cc:42:33: note: candidate is:
In file included from /home/chinachu/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../execsync.cc:3:
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/chinachu/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
make: *** [Release/obj.target/shell/execsync.o] エラー 1
make: ディレクトリ `/home/chinachu/chinachu/node_modules/execsync/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/chinachu/chinachu/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/home/chinachu/chinachu/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chinachu/chinachu/node_modules/execsync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/chinachu/chinachu/.nave/installed/0.12.0/bin/node" "/home/chinachu/chinachu/.nave/installed/0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! execsync@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execsync@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the execsync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls execsync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chinachu/chinachu/npm-debug.log
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
diff@1.0.8 node_modules/mocha/node_modules/diff
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
commander@2.3.0 node_modules/mocha/node_modules/commander
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
easy-table@0.2.0 node_modules/easy-table
minimist@0.0.8 node_modules/mocha/node_modules/mkdirp/node_modules/minimist
lolex@1.1.0 node_modules/sinon/node_modules/lolex
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
mkdirp@0.3.5 node_modules/mkdirp
traverse@0.3.9 node_modules/hoard/node_modules/binary/node_modules/chainsaw/node_modules/traverse
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
string@1.5.1 node_modules/string
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
debug@2.0.0 node_modules/mocha/node_modules/debug
└── ms@0.6.2
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
spdy@1.14.15 node_modules/spdy
formatio@1.1.1 node_modules/sinon/node_modules/formatio
└── samsam@1.1.2
jade@0.26.3 node_modules/mocha/node_modules/jade
├── commander@0.6.1
└── mkdirp@0.3.0
glob@3.2.3 node_modules/mocha/node_modules/glob
├── inherits@2.0.1
├── graceful-fs@2.0.3
└── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
http-auth@1.2.9 node_modules/http-auth
├── node-uuid@1.2.0
├── htpasswd@2.0.2 (commander@1.3.2, coffee-script@1.6.3)
└── htdigest@2.0.1 (commander@1.3.2, coffee-script@1.6.3)
mtwitter@1.5.3 node_modules/mtwitter
├── jape@0.0.3
├── fantail@0.2.1
├── underscore@1.6.0
├── pkginfo@0.3.0
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── request@2.34.0 (json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, mime@1.2.11, node-uuid@1.4.2, http-signature@0.10.1, form-data@0.1.4, tough-cookie@0.12.1, hawk@1.0.0)
xml2js@0.2.8 node_modules/xml2js
└── sax@0.5.8
/
> ws@0.4.32 install /home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: ディレクトリ `/home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build' に入ります
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: ディレクトリ `/home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build' から出ます
socket.io@0.9.17 node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
done.
Do you want to start chinachu services [Y/n]? Y
Starting chinachu-operator: OK.
Starting chinachu-wui: OK.
</pre>

一応Chinachuサービス自体は起動しましたが、不完全な状態でアップデートされており
不具合が出てきますよねこれ？

**Comment by kanreisa** [comment]
見た感じ特に問題はなさそうです。

既に使われていないモジュールのビルドに失敗しているだけなので、
rm -rf ./node_modules/execsync/
すればエラーが消えます。たぶん。

**Comment by falconws** [comment]
@kanreisa ありがとうございます。
提示して頂いたコマンドを叩いて該当ディレクトリを消した後再度
<pre>
./chinachu updater
</pre>
してみました。
<pre>
Do you want to run chinachu installer (fast) [Y/n]? Y
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)		  5) Node.js Modules	   9) libfdk-aac
2) Auto (fast)		  6) epgdump		  10) libogg
3) submodule		  7) libx264		  11) libvorbis
4) Node.js Environment	  8) libvpx		  12) libav
what do you install? > selected: Auto (fast)
removed `/home/chinachu/chinachu/.nave'
Installing Node using Nave...
--2015-02-18 23:19:12--  https://github.com/isaacs/nave/archive/master.tar.gz
github.com (github.com) をDNSに問いあわせています... 192.30.252.131
github.com (github.com)|192.30.252.131|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/isaacs/nave/tar.gz/master [続く]
--2015-02-18 23:19:13--  https://codeload.github.com/isaacs/nave/tar.gz/master
codeload.github.com (codeload.github.com) をDNSに問いあわせています... 192.30.252.145
codeload.github.com (codeload.github.com)|192.30.252.145|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 7625 (7.4K) [application/x-gzip]
`STDOUT' に保存中

100%[======================================>] 7,625       --.-K/s   時間 0s    

2015-02-18 23:19:14 (46.4 MB/s) - stdout へ出力完了 [7625/7625]

nave-master/nave.sh
ディレクトリを削除しました: `/home/chinachu/chinachu/.nave/nave-master'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
installed from binary
`/home/chinachu/chinachu/.nave/node' -> `/home/chinachu/chinachu/.nave/installed/0.12.0/bin/node'
`/home/chinachu/chinachu/.nave/npm' -> `/home/chinachu/chinachu/.nave/installed/0.12.0/bin/npm'
done.
Installing Node Modules using NPM...
npm WARN package.json opts@1.2.2 No repository field.
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
diff@1.0.8 node_modules/mocha/node_modules/diff
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
commander@2.3.0 node_modules/mocha/node_modules/commander
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
easy-table@0.2.0 node_modules/easy-table
minimist@0.0.8 node_modules/mocha/node_modules/mkdirp/node_modules/minimist
lolex@1.1.0 node_modules/sinon/node_modules/lolex
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
mkdirp@0.3.5 node_modules/mkdirp
traverse@0.3.9 node_modules/hoard/node_modules/binary/node_modules/chainsaw/node_modules/traverse
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
string@1.5.1 node_modules/string
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
debug@2.0.0 node_modules/mocha/node_modules/debug
└── ms@0.6.2
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/chinachu/chinachu/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
spdy@1.14.15 node_modules/spdy
formatio@1.1.1 node_modules/sinon/node_modules/formatio
└── samsam@1.1.2
jade@0.26.3 node_modules/mocha/node_modules/jade
├── commander@0.6.1
└── mkdirp@0.3.0
glob@3.2.3 node_modules/mocha/node_modules/glob
├── inherits@2.0.1
├── graceful-fs@2.0.3
└── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
xml2js@0.2.8 node_modules/xml2js
└── sax@0.5.8
http-auth@1.2.9 node_modules/http-auth
├── node-uuid@1.2.0
├── htdigest@2.0.1 (coffee-script@1.6.3, commander@1.3.2)
└── htpasswd@2.0.2 (coffee-script@1.6.3, commander@1.3.2)
 
> ws@0.4.32 install /home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: ディレクトリ `/home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build' に入ります
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: ディレクトリ `/home/chinachu/chinachu/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build' から出ます
socket.io@0.9.17 node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
mtwitter@1.5.3 node_modules/mtwitter
├── jape@0.0.3
├── fantail@0.2.1
├── underscore@1.6.0
├── pkginfo@0.3.0
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── request@2.34.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, mime@1.2.11, node-uuid@1.4.2, tough-cookie@0.12.1, http-signature@0.10.1, hawk@1.0.0, form-data@0.1.4)
done.
Do you want to start chinachu services [Y/n]? Y
Starting chinachu-operator: OK.
Starting chinachu-wui: OK.
</pre>

見てて気になるのは、
<pre>
curl: (22) The requested URL returned error: 404 Not Found
</pre>
* 何かをcurlで取得しようとして404が返ってきて取得に失敗していること
* npm WARN が大量に出ていること

ぐらいですが、いずれも無害と認識しておいて大丈夫ですか？

**Comment by kanreisa** [comment]
だいじょうぶでうｓ。

**Comment by falconws** [comment]
了解しました。
Issue Closeします。
