### ISSUE TITLE
node.js で不具合？

### ISSUE THREAD

**Issue by airwhite** [kanreisa/Chinachu#145]
数日前にNode.jsがバージョンアップして仕様変更があったそうですがその関連でしょうか？
Node.jsのモジュールで更新が正しく行われていないようです。
一応 .nave/npm cache clean を実行してみたけど効果ありませんでした。

chinachu@pt3:~/chinachu$ ./chinachu installer
Chinachu Installer Menu:
[!] These are installed under all /home/chinachu/chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)            5) Node.js Modules       9) libfdk-aac
2) Auto (fast)            6) epgdump              10) libogg
3) submodule              7) libx264              11) libvorbis
4) Node.js Environment    8) libvpx               12) libav
what do you install? > 5
selected: Node.js Modules
Installing Node Modules using NPM...
npm WARN package.json opts@1.2.2 No repository field.

> execsync@0.0.5 install /home/chinachu/chinachu/node_modules/execsync
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp: binding.gyp not found (cwd: /home/chinachu/chinachu/node_modules/execsync) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/chinachu/chinachu/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/home/chinachu/chinachu/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chinachu/chinachu/node_modules/execsync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/home/chinachu/chinachu/.nave/installed/0.12.0/bin/node" "/home/chinachu/chinachu/.nave/installed/0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! execsync@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execsync@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the execsync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls execsync
npm ERR! There is likely additional logging output above.

**Comment by kanreisa** [comment]
こちらを参照してください。 #131

**Comment by kanreisa** [comment]
間違えました。こちらを参照してください #140

**Comment by airwhite** [comment]
お手数をおかけしました。
#140 の rm -rf ./node_modules/execsync/ で対応後に
./chinachu update -f を実行したところ

chinachu@pt3:~/chinachu$ ./chinachu update -f
module.js:338
    throw err;
          ^
Error: Cannot find module 'opts'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/chinachu/chinachu/app-scheduler.js:31:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

と出ましたので rm -rf ./node_modules/otps/ した後でモジュールを更新。
無事に update -f 出来ました。
ありがとうございました m(_ _)m

**Comment by kanreisa** [comment]
よかったですー。
