### ISSUE TITLE
番組表の再取得ができなくなりました。

### ISSUE THREAD

**Issue by angel646** [kanreisa/Chinachu#152]
チャンネル設定のため、何度か ./chinachu update -f を実行していたら
util.error: Use console.error instead
ERROR: Scheduler is already running.
とのエラーが表示され一切更新できなくなりました。
また、番組表でのチャンネルのかぶりはどうすれば解消されるでしょうか。
![default](https://cloud.githubusercontent.com/assets/11473805/6651628/3d1899ae-ca8e-11e4-9d1b-1ecdee022083.jpg)

**Comment by kanreisa** [comment]
そのエラーメッセージの通りだと思います。
少し待てば使えるようになります。
お急ぎならschedulerプロセスをkillしてください。

チャンネルかぶりは設定ファイルのミスかもしれませんねぇ。

**Comment by angel646** [comment]
番組表の更新は少し待ったら使えるようになりました。
チャンネルかぶりは設定ファイルをいじれば減らすことが出来ました。
ありがとうございました。

**Comment by angel646** [comment]
参考までに
大阪地上波
    { "type": "GR", "channel": "24" },
    { "type": "GR", "channel": "13" },
    { "type": "GR", "channel": "26" },
    { "type": "GR", "channel": "16" },
    { "type": "GR", "channel": "23" },
    { "type": "GR", "channel": "15" },
    { "type": "GR", "channel": "18" },
    { "type": "GR", "channel": "17" },
    { "type": "GR", "channel": "14" },
    { "type": "GR", "channel": "19" },
    { "type": "GR", "channel": "22" }
