### ISSUE TITLE
recordedCommandを使用して自動エンコードができない

### ISSUE THREAD

**Issue by angel646** [kanreisa/Chinachu#153]
recordedCommandの機能を利用して自動でシェルプログラムを動作するように設定したのですが。
ffmpegでのエンコードのみが作動しません。
ログにはしっかりとend,と記録されていました。
事前にffmpegのコマンドのエラーチェックはしています。

#!/bin/sh
echo "$1" >> hoge.txt
day=$(date)
category=$(echo $2 | jq '.category')
title=$(echo $2 | jq '.title')
episode=$(echo $2 | jq '.episode')
cat hoge.txt

case $category in
        "\"anime\"")
                echo date "${day} animeEnc" >> hoge.txt
                ffmpeg -i $1 -b:v 3000k -ab 180k "/media/Server/video/anime/${title}.mp4"
                ;;
        "\"drama\"")
                echo "${day} dramaEnc" >> hoge.txt
                ffmpeg -i $1 -b:v 4000k -ab 200k "/media/Server/video/drama/${title}.mp4"
                ;;
        *)
                ffmpeg -i $1 -ab 128k "/media/Server/video/${title}.mp4"
                echo "${day} defaultEnc" >> hoge.txt
                ;;
esac

$day=$(echo date)
echo "${day} ${title}" >> hoge.txt
echo "${day} ${episode}" >> hoge.txt
echo "${day} ${category}" >> hoge.txt
echo "${day} end" >> hoge.txt
cat hoge.txt
exit

**Comment by kanreisa** [comment]
どうしてffmpegコマンドのログは取っていないのですか。

**Comment by angel646** [comment]
ログをとってみた結果コマンドが見つからないみたいです。
./recorded-script: 21: ./recorded-script: ffmpeg: not found
ハッシュの再取得をしましたが、結果は変わりませんでした。

**Comment by kanreisa** [comment]
PATHを通せばよいと思いますです

**Comment by angel646** [comment]
ffmpegをPATH指定すれば実行できましたが、以下のエラーが表示されるようになりました。

ffmpeg version git-2015-03-16-3e48616 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --prefix=/home/chinachu/ffmpeg_build --extra-cflags=-I/home/chinachu/ffmpeg_build/include --extra-$
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 28.100 / 56. 28.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 12.100 /  5. 12.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
"/media/Server/rec/2064.m2ts": No such file or directory

/media/Server/rec/2064.m2tsにファイルは存在しており、アクセス権限も777にスクリプトの頭で書き換えています。

**Comment by kanreisa** [comment]
そのffmpegはご自分でビルドされたものですか？だとしたら良く分かりません。

ところで、Chinachuが持っているavconvを使うこともできます。この場合PATHは通さなくてよいです。

```sh
#!/bin/sh

avconv -y -threads:v:3 -threads:a:1 -i "$1" \
       -preset:v ultrafast -tune ssim -crf 20 \
       -profile:a aac_he -b:a 96k -afterburner 1 \
       "$1.mp4" > "$1.txt" 2>&1

exit
```

いかがでしょうか。

**Comment by angel646** [comment]
avconv を使用すればエンコードすることが出来ました。
ffmpegはいろいろと不安定ですね。
何から何まで、ありがとうございました。

**Comment by kanreisa** [comment]
:sunny:
