### ISSUE TITLE
録画済画面の改善点

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#154]
現在の構成では、録画済画面から再生するまでに、3回クリックする必要があります。

できれば、右1回クリックで表示されたメニューから再生が選べた方が便利だと思います。
再生の設定を選択する必要があるから、現状の構成となっていますが、見る環境というのは、自宅LAN、モバイルの2つと考えていいと思いますから、高速と低速の設定をconfigに書いておき、「通常再生」と「モバイル再生」をメニューから選んで再生できると便利です。

録画したものを再生という作業が、このシステムでは一番多いと思います。これが3ステップというのは、かなり重たく感じています。

**Comment by miyukki** [comment]
Chinachuはリアルタイムエンコードなので、MPEG−DASHのように最初に帯域を判定してその帯域にあったビットレートで再生とかもいいかも（ステップとは別にして

**Comment by simplelife0530** [comment]
帯域判定して、最適再生、いいですね。

それから、メニューから再生を選ぶより、録画済画面の録画ファイルリストで、行ごとに「再生」ボタンをつけたほうがいいですね。

**Comment by kanreisa** [comment]
フィードバックありがとうございました。前向きに検討します。
