### ISSUE TITLE
録画済ファイルの削除の改善点

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#155]
現在、録画済画面から右クリックで、「録画ファイルの削除」を選択することができるようになっています。

録画システムで録画ファイルの削除というのは、かなり頻繁に行われる操作（人や使い方でもかなり差がありますが、TSファイルは特に多いと思います。）なので、メニューでひとつひとつ行うのは、かなり苦痛です。

やはり録画済画面に、ファイルごとのチェックボックスを設けて、「選択ファイルの削除」という形式にした方が使いやすいと思います。

ところで、「録画履歴の削除」という機能は、使うことがあるのでしょうか？

もちろんOS側のファイリング機能から、一括操作でファイルの削除などを行い、「クリーンアップの実行」を行えばいいということかもしれません。しかし、ブラウザからの操作で全て行えるという利便性から考えると、ファイルの削除、ファイルの並べ替え、フォルダへの振り分けなどは、本システムのブラウザ画面からできるようにした方が、便利です。

**Comment by kazu335i** [comment]
ファイルのcopyはOS側からが便利ですよ？moveしたら「録画履歴の削除」一発でクリーンできますし。

**Comment by simplelife0530** [comment]
それぞれ人によって使い方が違うと思いますが、基本ブラウザだけで操作する使い方ですので、無理だと思います。

**Comment by kanreisa** [comment]
現行リリースはブラウザだけで操作するような設計思想ではありません。
権限も限定されていますので、ファイル操作のUIも控えめになっています。
チェックボックスを設ける案についてはPR可です。
その他の要望については現行リリースでは改善を予定していません。
