### ISSUE TITLE
epgrecからの乗り換えでエラーが出て苦戦中

### ISSUE THREAD

**Issue by raou-10** [kanreisa/Chinachu#156]
Centos7にインストール中なのですが情報が少なく苦戦しております。

# ./chinachu installer
Chinachu Installer Menu:
[!] These are installed under all /root/Chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)            5) Node.js Modules       9) libfdk-aac
2) Auto (fast)            6) epgdump              10) libogg
3) submodule              7) libx264              11) libvorbis
4) Node.js Environment    8) libvpx               12) libav
what do you install? > 1

　　　―――　略　―――

--2015-03-21 10:07:32--  https://github.com/isaacs/nave/archive/master.tar.gz
github.com (github.com) をDNSに問いあわせています... 192.30.252.130
github.com (github.com)|192.30.252.130|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/isaacs/nave/tar.gz/master [続く]
--2015-03-21 10:07:32--  https://codeload.github.com/isaacs/nave/tar.gz/master
codeload.github.com (codeload.github.com) をDNSに問いあわせています... 192.30.252.147
codeload.github.com (codeload.github.com)|192.30.252.147|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 特定できません [application/x-gzip]
`STDOUT' に保存中

    [ <=>                                                                                            ] 7,644       --.-K/s 時間 0s      

2015-03-21 10:07:33 (116 MB/s) - stdout へ出力しました [7644]

nave-master/nave.sh
ディレクトリを削除しました: `/root/Chinachu/.nave/nave-master'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
installed from binary
`/root/Chinachu/.nave/node' -> `/root/Chinachu/.nave/installed/0.12.0/bin/node'
`/root/Chinachu/.nave/npm' -> `/root/Chinachu/.nave/installed/0.12.0/bin/npm'
done.

と302や404が出てしまってるせいか上手いこと起動しません。

# ./chinachu service wui execute
util.error: Use console.error instead
**SELF-REGULATION WARNING**: If you want to access from outside of LAN, Please activate TLS.
info: socket.io started
info: socket.io started
21 Mar 10:05:16 - HTTP Server Listening on { address: '0.0.0.0', family: 'IPv4', port: 10772 }
21 Mar 10:05:16 - HTTP Open Server Listening on { address: '127.0.0.1', family: 'IPv4', port: 20772 }
21 Mar 10:05:16 - READ: `/root/Chinachu/rules.json` is updated.
21 Mar 10:05:16 - READ: `/root/Chinachu/data/recorded.json` is updated.
21 Mar 10:05:16 - READ: `/root/Chinachu/data/recording.json` is updated.
21 Mar 10:05:16 - READ: `/root/Chinachu/data/reserves.json` is updated.
21 Mar 10:05:16 - READ: `/root/Chinachu/data/schedule.json` is updated.

# cat ./log/wui
util.error: Use console.error instead
**SELF-REGULATION WARNING**: If you want to access from outside of LAN, Please activate TLS.
info: socket.io started
info: socket.io started
21 Mar 08:06:25 - HTTP Server Listening on { address: '0.0.0.0', family: 'IPv4', port: 10772 }
21 Mar 08:06:25 - HTTP Open Server Listening on { address: '127.0.0.1', family: 'IPv4', port: 20772 }
21 Mar 08:06:25 - READ: `/root/Chinachu/rules.json` is updated.
21 Mar 08:06:25 - READ: `/root/Chinachu/data/reserves.json` is updated.
21 Mar 08:06:25 - READ: `/root/Chinachu/data/recording.json` is updated.
21 Mar 08:06:25 - READ: `/root/Chinachu/data/recorded.json` is updated.
21 Mar 08:06:25 - READ: `/root/Chinachu/data/schedule.json` is updated.

何が原因なのかググっても情報が少なく苦戦しております。
どなたかわかる方いましたら教えて下さい。

**Comment by miyukki** [comment]
何がうまくいかないのでしょうか、見てる限りnodeはインストールに成功し正常に起動しているような気がするのですが。

**Comment by kanreisa** [comment]
404が出てしまうのは nave の仕様で、その後普通に `installed from binary` と出ているので問題ないかと
※ 302 Found とは → http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by simplelife0530** [comment]
CentOS6.6でchinachuを稼働していますので、何か問題があればお答えできると思います。

まず、何が問題なのか投稿された内容から状況がつかめません。ローカルPCのブラウザからhttp://127.0.0.1:10772/にアクセスして、何も表示されないということですか？

**Comment by raou-10** [comment]
./chinachu update -f
で番組表を取得しても放置してても
http://192.168.100.xx:10772/ にアクセスして
http://192.168.100.xx:10772/#!/schedule/table/ を見ても何も表示されてないんです。

**Comment by miyukki** [comment]
http://192.168.100.xx:10772/ にはchinachuのUIは表示されてます？
設定ファイルは自分のチューナーの環境に合わせましたか？

**Comment by simplelife0530** [comment]
raou-10さん、
もし別のPCから表示させたいなら、ファイアウォールで10772は開放してますか。

システム＞管理＞ファイアウォールは、CentOS6系ですが、７ではかなり変わってましたね。

**Comment by simplelife0530** [comment]
確かに、miyukkiさんの言うとおり、何も表示されていない、という答えは困りモノです。UIが表示されているなら、また対応は異なります。画面キャプチャで、ここにアップロードしたらわかりやすいですね。

実は、私も昨日まで番組表が表示されず、困っていました。recpt1が悪かったようで、あるサイトにあった情報から、recpt1を入れ替えたら、解決しました。

**Comment by simplelife0530** [comment]
情報はこれです。

実際に実行してみると　番組表がとれない
EPG: データが空 (result.tv.channel is undefined)

調べてみるとrecpt1を入れ替えるといいらしい
stz2012/recpt1 ・ GitHub
wget https://github.com/stz2012/recpt1/archive/master.zip
unzip master.zip
(cd ./master-recpt1/recpt1)
cd /recpt1-master/recpt1
./autogen.sh
./configure --enable-b25
make
make install

**Comment by raou-10** [comment]
おはようございます。昨晩、一応成功しました。
＞EPG: データが空 (result.tv.channel is undefined)
このエラーが出てて躓いてました。
recpt1を入れ替えで無事に成功です。

あとちょっと気づいたのですが、BSとCSのチューナーは同じ（PT3使用）なのですが
一枚刺しだとBS/CSで計2番組しか録画予約出来ないのに、3番組以上録画予約しても警告等無いんですね！？

**Comment by simplelife0530** [comment]
raou-10さん

解決されてよかったですね。

同時録画があふれても、何も警告でないこと、私も確認しました。
2枚刺しなので、地上波4チャンネル同時録画可能な状態で、5番組手動予約したところ
5番目は、デバイスが割り当てられない状態で、止まっているようです。

ルールで予約した場合の挙動が確認できていませんが、予約したのに録画されないことが起こる可能性もあります。
![chinachu5recording](https://cloud.githubusercontent.com/assets/8540097/6768329/f9cecfa4-d0a7-11e4-85bc-4175ceaca9b4.PNG)

**Comment by kanreisa** [comment]
予約の後はスケジューラーを実行して競合を検出することをお勧めします。
競合した場合予約から外れてログに残ります。
