### ISSUE TITLE
ルールの設定があまり親切ではない。

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#157]
ルールの設定項目は、もう十分とは思いますが、ルールの検証ができず、予約状況を判断するまで、このルールが自分の思った通りなのか、検証できないのは、あまり使い勝手が良いとはいえない。

番組表の改善が話題になっていたが、番組表からの予約は、既に現在のTVで十分できるレベルまできているので、そこがchinachuのうりどころではないだろう。

windowsで完成されたTVRockを超えるような使い勝手が、linux上のchinachuには要求されると、個人的には考えている。

そこで、残念なのが、ルールの設定である。せっかく検索機能があるのだから、検索で得られた結果が自分の望む録画リストだったならば、それをルールとして登録できるのが自然な流れだろう。

まあ、ちょっと作ればすぐに実現できる機能だから、問題無いとは思いますが。。。

**Comment by simplelife0530** [comment]
更に、ルールによってどの予約がされているか、
逆にこの予約は、どのルールによって行われたのか、これが一目瞭然でないととても不便です。
一つのルール設定とその結果が一画面で表示できることが望ましい。「ルール検証」と「ルール設定」のボタンがあれば、検証したいルールでどれが予約されるか確認し、望み通りのルールができたら、ルール設定ができる、という構成が使いやすい。

また、予約済画面でも、この予約がどのルールによって行われたのか、表示されるとわかりやすい。

**Comment by kanreisa** [comment]
フィードバックありがとうございました。次期リリースではそのような仕様になってます。
