### ISSUE TITLE
タイトル表示がおかしい

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#158]
予約済画面や録画済画面で表示されるタイトルが、中途半端な表示。番組名も確認できないものがある。

クリックすれば、完全なタイトルに、きちんと番組名が表示されているのに、不思議としかいいようがない。

予約済画面も録画済画面も、タイトルは、完全なタイトルでいいのではないでしょうか。

**Comment by kanreisa** [comment]
go #134
