### ISSUE TITLE
chinachuのネックは、recpt1とドライバ。

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#159]
chinachuは軽くてシンプルで、とても使いやすい。

問題がある、とすれば、recpt1とPT2,PT3のドライバにある。スリープ後にロックされるのも、ドライバの問題のようだ。

そこで、こういう不良品のトラブルに巻き込まれないようにするために、chinachuから、recpt1やドライバのテストができるようにすれば、切り分けも簡単になる。

（１）recpt1で地上波デジタルやBSが録画できる。
（２）./chinachu update -f で番組取得ができる。

これをchinachuの中でボタンをクリックするだけで、チェックできる機能が必要だと思います。
コマンドを打ち込むのは億劫だし、そもそもリモートでブラウザ経由でチェックできれば、大変便利でしょう。

**Comment by kanreisa** [comment]
現行リリースでは対応できません。

次期リリースでは:

* 録画コマンドは継続的に実行されるため問題があれば直ちに知らされる
* `./chinachu update -f` は廃止

といった仕様になります。フィードバックありがとうございました。
