### ISSUE TITLE
不具合と要望

### ISSUE THREAD

**Issue by sinatiku** [kanreisa/Chinachu#162]
・ダッシュボードの文字が重なって表示される

・ルールに毎週何曜日が対象の録画か選択できるようにして欲しい

・ルールがグレーと白の背景色で縞模様になってますがグレーの部分にあるルールを無効にしても
ほとんど色が変わらずわかりづらい。

ルールがアバウトに設定してるせいもあるのですが、CSとかだと同じ番組が週に10回ほど
放送するので予約済みに何度も設定されてしまいます。
手動でスキップして録画のキャンセルをしているのですが、チェックボックスが無いので
1つ1つスキップしていかないといけません。チェックボックスで一括でスキップとか出来ませんか？
重複してる番組は、自動でキャンセル出来ればいうことが無いんですが。。。

**Comment by sinatiku** [comment]
＞・ダッシュボードの文字が重なって表示される
○件の録画済とかの文字です。重なってて読めないです。すいません。

**Comment by kanreisa** [comment]
これを修正する体力がないため、Usushioを待ってください。しかしながらPRは受け付けています :smile:

その他重複:

> ・ダッシュボードの文字が重なって表示される

#78

> ・ルールに毎週何曜日が対象の録画か選択できるようにして欲しい

#56
