### ISSUE TITLE
ルールに関する不具合

### ISSUE THREAD

**Issue by raou-10** [kanreisa/Chinachu#165]
チャンネル新規作成
で対象フラグの新のみをチェックして新しい番組をすべて録画するつもりでいたのですが
ルールに追加しても録画予約されません。

**Comment by kanreisa** [comment]
もう少し具体的にお願いします。

**Comment by raou-10** [comment]
ルール追加で
新規作成で対象フラグ「新」のみをチェック。
その他は無指定。4月から始まる新番組をすべて録画しようとしたところ
録画が予約出来ない。これでわかりますか？？

**Comment by kanreisa** [comment]
![](https://yabumi.cc/14c57e16875f3ca1649c17fb.png)
こうですか？わかりません。

**Comment by raou-10** [comment]
そうです。

**Comment by kanreisa** [comment]
スケジューラーを実行ボタンを押すかしばらく放置すると予約されます。
