### ISSUE TITLE
libavのインストールが失敗する

### ISSUE THREAD

**Issue by chiko23** [kanreisa/Chinachu#168]
libx264関連でエラーが出てmakeできませんでした。
PKG_CONFIG_PATHを設定したところ無事にコンパイルできました

'config.log'

'''
Package x264 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x264.pc'
to the PKG_CONFIG_PATH environment variable

No package 'x264' found
ERROR: libx264 not found
'''

**Comment by kanreisa** [comment]
merged to #144
