### ISSUE TITLE
番組表データの取得でエラーが発生します

### ISSUE THREAD

**Issue by satn** [kanreisa/Chinachu#169]
バグなのか、仕様が変わったからなのか分からないのですが、chinachuを最新にしたら番組表データの取得でエラーが出るようになりました。
ログを見る限り、以前のchinachuでは、1チャンネルずつデータ取得を順々に行っていたと思いますが、最新では取得対象のチャンネルすべてのデータ取得プロセスを一気に立ち上げるように変更されていませんか？
それともtuner.0.lockが作成できないか意図せず消えてるとか、別の原因でしょうか？
アドバイスをお願いします。

以下はchinachu最新化後のschedulerログです。

31 Mar 00:00:24 - GETTING EPG.
31 Mar 00:00:24 - [0] {"type":"GR","channel":"27","n":0}
31 Mar 00:00:24 - [0] LOCK: PT3-T1 (n=0)
31 Mar 00:00:24 - [0] SPAWN: recdvb --sid epg 27 - - (pid=5853)
31 Mar 00:00:24 - [0] STREAM: /tmp/chinachu-tmp-i7w05xnc.m2ts
31 Mar 00:00:25 - [1] {"type":"GR","channel":"26","n":1}
31 Mar 00:00:25 - [1] LOCK: PT3-T1 (n=0)
31 Mar 00:00:25 - [1] SPAWN: recdvb --sid epg 26 - - (pid=5859)
31 Mar 00:00:25 - [1] STREAM: /tmp/chinachu-tmp-i7w05xzi.m2ts
31 Mar 00:00:25 - [2] {"type":"GR","channel":"25","n":2}
31 Mar 00:00:25 - [2] LOCK: PT3-T1 (n=0)
31 Mar 00:00:25 - [2] SPAWN: recdvb --sid epg 25 - - (pid=5860)
31 Mar 00:00:25 - [2] STREAM: /tmp/chinachu-tmp-i7w05y4q.m2ts
:
:
31 Mar 00:00:26 - STATUS: { completed: 0, waiting: 8, worked: 8, running: 8 }
31 Mar 00:00:26 - STATUS: { completed: 0, waiting: 0, worked: 8, running: 8 }
31 Mar 00:00:26 - STATUS: { completed: 0, waiting: 0, worked: 8, running: 8 }
:
:
31 Mar 00:00:26 - [1] UNLOCK: PT3-T1 (n=0)
31 Mar 00:00:26 - [1] EXEC: epgdump (pid=5867)
31 Mar 00:00:26 - { [Error: ENOENT, no such file or directory './data/tuner.0.lock']
  errno: -2,
  code: 'ENOENT',
  path: './data/tuner.0.lock',
  syscall: 'open' }
31 Mar 00:00:26 - [2] EXEC: epgdump (pid=5868)
31 Mar 00:00:26 - { [Error: ENOENT, no such file or directory './data/tuner.0.lock']
  errno: -2,
  code: 'ENOENT',
  path: './data/tuner.0.lock',
  syscall: 'open' }
:
:
31 Mar 00:00:28 - [0] #recdvb: pid = 5853 device = /dev/dvb/adapter0/frontend0 Using DVB card "Siano Mobile Digital MDTV Receiver" tuning to 557143 kHz polling..ok SNR: 300  Recording... Available sid = 1024 1025 1408 65520  Chosen sid    = Available PMT = 0x1f0 0x3f0 0x1fc8 0x1cf0
31 Mar 00:00:28 - [1] #recdvb: pid = 5859 cannot open frontend device
31 Mar 00:00:28 - [2] #recdvb: pid = 5860 cannot open frontend device
:
:
31 Mar 00:00:29 - [2] EPG: データが空 (result.tv.channel is undefined)
31 Mar 00:00:29 - [2] -- (retrying, residue=2)
31 Mar 00:00:29 - UNLINK: /tmp/chinachu-tmp-i7w05xzi.m2ts
31 Mar 00:00:29 - [1] EPG: データが空 (result.tv.channel is undefined)
31 Mar 00:00:29 - [1] -- (retrying, residue=2)
:
:

**Comment by sinatiku** [comment]
ただチューナがロックしてるのとrecpt1のバージョン違いかと。
ここのwikiにも載ってるし、ググってもHITまくり。

**Comment by raou-10** [comment]
チューナーのロック解除して
データを再取得しても

    { "type": "BS", "channel": "291", "_ch_name": "NHK-G東京" },
    { "type": "BS", "channel": "292", "_ch_name": "NHK-E東京" },
    { "type": "BS", "channel": "294", "_ch_name": "日本テレビ" },
    { "type": "BS", "channel": "295", "_ch_name": "テレビ朝日" },
    { "type": "BS", "channel": "296", "_ch_name": "TBS" },
    { "type": "BS", "channel": "297", "_ch_name": "テレビ東京" },
    { "type": "BS", "channel": "298", "_ch_name": "フジテレビ" },

これらのチャンネルだけ今日の12:00からデータが取得出来ません。
私だけでしょうか？？

**Comment by kanreisa** [comment]
@satn 
かなり昔から並列取得するようになっていますよ。
* tuners 設定が間違っていないか確認
* [operRecCmdSpan](https://github.com/kanreisa/Chinachu/wiki/Configuration) を設定する
* OSそのものを再起動する

@raou-10 
こちらでは全くサポートできませんので、地デジ難視対策衛生放送受付センターへお問い合わせください。

**Comment by satn** [comment]
更新前はうまくいっていたのでtuners設定の問題ではないです。
私の環境では同時に受信できるチューナーデバイスは1つしかありません。
また、recdvb(recpt1のDVBドライバ対応版)はデバイス使用中の場合は使用可能になるのを待たずにエラー終了となります。
なので、番組データ取得が全部エラーになるのではなく、1チャンネルだけ成功します。よって最初からロックしているわけでもありません。

別の質問になりますが、chinachuが使用を想定しているrecpt1は例えば10チャンネル登録があったら、同時に10チャンネルデータ取得にいくのでしょうか？それともrecpt1はデバイスが全部使用中なら待ってくれることを想定していますか？

**Comment by kanreisa** [comment]
後者です。

**Comment by satn** [comment]
確認させてください。以下の認識で合ってますか？
・chinachuはrecpt1に10チャンネル（登録した数分）同時に取得に行かせる。
・デバイス使用中のときに待ってくれるのはrecpt1であり、chinachuは全く待つことはしない。

**Comment by kanreisa** [comment]
合っていません。

**Comment by satn** [comment]
じゃあ、何が合ってないのかな？

**Comment by kanreisa** [comment]
> ・chinachuはrecpt1に10チャンネル（登録した数分）同時に取得に行かせる。
そのような仕様ではありません。

> ・デバイス使用中のときに待ってくれるのはrecpt1であり、chinachuは全く待つことはしない。
デバイスの使用状況については全く関知していません。プロセスの管理しかしません。

**Comment by satn** [comment]
>>    ・chinachuはrecpt1に10チャンネル（登録した数分）同時に取得に行かせる。
>
>そのような仕様ではありません。

前に「並列取得する」って書いてるからそういうことだと思ったけど違うんですか？

>>    ・デバイス使用中のときに待ってくれるのはrecpt1であり、chinachuは全く待つことはしない。
>
>デバイスの使用状況については全く関知していません。プロセスの管理しかしません。

じゃあ、前半は合ってますね。後半は、chinachuはプロセスの終了は待つよ、プロセス管理してるから。って意味ですかね。

結局のところ、ロックファイルとか作っておきながら、何のためのロックファイルなんでしょうか？？
面倒な部分は全てrecpt1にお任せだし。

**Comment by kanreisa** [comment]
なぜ喧嘩腰なのかは知りませんが、

* 利用可能なチューナーを使用して並列に取得
* ロックファイルというよりも最近の意味合い的にはPIDファイルです。Chinachuが内部的にプロセスを管理するために利用します。

これでいいすか？

**Comment by satn** [comment]
> ・利用可能なチューナーを使用して並列に取得
「利用可能なチューナー」かどうかを判断するのはchinachuですか？つまり、tunersに1エントリしかない場合、1プロセス起動したらPIDファイルを作成し、その間は別のプロセスは起動しない。起動中だったプロセスが終了し、PIDファイルが削除されたら、新しいプロセスが起動する、、という流れでしょうか？

**Comment by kanreisa** [comment]
はい。だから、仰っていた

> 更新前はうまくいっていたのでtuners設定の問題ではないです。

これ、疑わしいですね。見直してください。

**Comment by satn** [comment]
なんでそうなるかな〜
config.jsonは前から変えてません。
やっと中身のある回答してくれたので、その内容を踏まえると以下あたりが真相だと思いますけどね。

31 Mar 00:00:26 - { [Error: ENOENT, no such file or directory './data/tuner.0.lock']
errno: -2,
code: 'ENOENT',
path: './data/tuner.0.lock',
syscall: 'open' }

**Comment by kanreisa** [comment]
ちょっとtuners設定を見せてください。一つずつみていきましょう。

**Comment by satn** [comment]
{
  "recordedDir" : "./recorded/",
  "temporaryDir": "/tmp/",
  
  "wuiPort"        : 10772,
  "wuiHost"        : "0.0.0.0",
  "wuiTlsKeyPath"  : null,
  "wuiTlsCertPath" : null,
  "wuiOpenServer"  : false,
  "wuiOpenPort"    : 20772,
  "wuiPreviewer"   : true,
  "wuiStreamer"    : true,
  "wuiFiler"       : true,
  "wuiConfigurator": true,
  
  "recordedFormat": "[<date:yymmdd-HHMM>]<title>.m2ts",
  
  "tuners": [
    {
      "name"        : "PT3-T1",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recdvb --b25 --strip --sid <sid> <channel> - -"
    }
  ],
  
  "channels": [
    { "type": "GR", "channel": "27" },
    { "type": "GR", "channel": "26" },
    { "type": "GR", "channel": "25" },
    { "type": "GR", "channel": "24" },
    { "type": "GR", "channel": "22" },
    { "type": "GR", "channel": "23" },
    { "type": "GR", "channel": "21" },
    { "type": "GR", "channel": "32" }
  ]
}

**Comment by satn** [comment]
"tuners": [
    {
      "name"        : "PT3-T1",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recdvb --b25 --strip --sid &lt;sid&gt; &lt;channel&gt; - -"
    }
  ],

**Comment by kanreisa** [comment]
tuners設定は問題ないように見えますね。

そもそも.lockファイルが作成できていない説がありますね。
スケジューラー実行中は.lockファイルが./data/ディレクトリに絶え間なく存在することになりますが

確認できますか？

**Comment by satn** [comment]
operatorサービスを再起動してみたら、tuner.0.lockが一瞬作成され、一秒もしないくらいで削除され、また、数秒？すると作成され、、となっていました。

**Comment by kanreisa** [comment]
インストールディレクトリへ cd し
```
.nave/node -v
```
なんと出力されますか

**Comment by satn** [comment]
v0.10.38
ですね。
もしかしてnodeのバージョン依存ですか。。v0.12.0はRasPi(ARM)では不具合があってコアダンプになってしまうので古いのを使ってました。ただ、v0.11.5というのも試したけど、コアダンプにはならないものの、同じロックファイルのエラーが出ていたはず。

**Comment by kanreisa** [comment]
https://github.com/kanreisa/Chinachu/blob/master/package.json#L46-L48
installer は使わなくても良いので、上記の仕様に合うようにご用意ください。

**Comment by satn** [comment]
そうですか、、仕様外の環境でエラー発生だったようで申し訳なかったです。
これはARMで元どおりnodeが動くようになるまでどうにもなりませんね。
ありがとうございました。

**Comment by kanreisa** [comment]
よろしくお願いいたします。
