### ISSUE TITLE
ルールのバルク削除にバグがある

### ISSUE THREAD

**Issue by airwhite** [kanreisa/Chinachu#172]
いつも楽しく利用させて頂いております。開発に携わる皆様、ありがとうございます。
そろそろ春の新番組が始まるので、ルールを削除していて気づいたのですが
添付画像のようにルールの一覧がある時に、９番と１０番を選んで削除すると
まず、９番を消すとルール番号の振り直しが行われて、１０番を消そうとすると
404 not found になり、１０番は削除されずに残ったままになります。
もしも、１１番目があった時は、９番を消すと１１番目は１０番になり、
消す必要がなかった１１番も削除されてしまうことになります。
ルールを削除する際に大きな番号から削除するようにならないでしょうか。
![rule-list](https://cloud.githubusercontent.com/assets/5238021/6982546/1344a076-da4e-11e4-8d7b-bbe79f734788.png)

**Comment by kanreisa** [comment]
大変ご不便をおかけいたしました。修正いたしました。

**Comment by airwhite** [comment]
おぉ早い。ありがとうございました m(_ _)m
