### ISSUE TITLE
久しぶりにロックした

### ISSUE THREAD

**Issue by raou-10** [kanreisa/Chinachu#176]
チューナーが久々にロックした
6 Apr 22:00:00 - WARNING: CS 利用可能なチューナーが見つかりません (存在しないかロックされています) (5秒後に再試行)
と大量に埋め尽くすログorz
再思考も大切だと思うけど
ls /dev/ | grep pt3
でデバイスが存在するか確認して
存在するなら
./chinachu unlock
等を自動で実行して欲しい。

**Comment by kanreisa** [comment]
チューナーが存在するかどうかではなく、そのチューナーが今使用されてるか否かが問題で、もしチューナーを使用していたプロセスが存在しない状態であれば正常にアンロックされます。 

* unlock コマンドは特殊なケースを除いて非推奨です。
* 手動予約の後はスケジューラーを実行します。
* 録画メインの場合はライブ視聴は使用しない。

とりあえずクローズしておきますが 、他に何かあればリオープンしていただければと思います。
