### ISSUE TITLE
バージョニングの導入

### ISSUE THREAD

**Issue by mzyy94** [kanreisa/Chinachu#177]
Chinachuのクライアントを製作しようかと思っているのですが、APIに変更があったり修正があったりしても、tagやpackage.jsonのバージョン情報に変更がないのが心配で、なかなか取りかかれません。
今後APIの変更があった際に、何を基準にそのクライアントがサポートするChinachuのリリースを示せば良いのでしょうか。
また、APIの変更に追従する点以外にも、現在のChinachuのバージョンがいくつであるかがわからないのも如何なものかと思います。
セマンティックバージョニングを採用し、クライアントに「Chinachuバージョン○.○.○対応」といった記述ができるようにするのが望ましいと思っているのですが、どうでしょうか。

**Comment by kanreisa** [comment]
その問題は常に認識していて、Airでは導入予定です。

**Comment by mzyy94** [comment]
了解です👍
Airの公開まではAPIに大幅な変更は加えられないという想定をしているのですが、その点いかかでしょう。

**Comment by kanreisa** [comment]
その認識で合っています。バグの修正以外はありません。

**Comment by mzyy94** [comment]
了解です:+1:
