### ISSUE TITLE
Windows 7 + Internet Explorer 11で、録画ファイルのストリーミング再生に失敗する

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#179]
Chinachuをmaster最新版に更新して使用しています。
Windows 7 SP1のIE11で録画ファイルの「再生」ボタンを押し、
ストリーミング再生しようとしたところ失敗します。

クライアント環境：
Windows 7 SP1 6.1.7601
Internet Explorer 11.0.9600.17728(更新バージョン：11.0.18)
VLC 2.2.0
Flash Player ActiveX 17.0.0.169

1.M2TSの場合
映像コーデック→無変換、H.264、MPEG-2
音声コーデック→無変換、AAC、Vorbis

いずれの組み合わせであっても「MPEG2-TSコンテナの再生にはVLC Web Pluginが必要です。」と、
エラーが表示され再生不可になります。

2.MP4の場合
映像コーデック→H.264
音声コーデック→AAC

ブラウザ上で再生画面が開くのですが「エラー：ビデオタイプがサポートされていない、またはファイルパスが無効です」と、エラーが表示され再生不可になります。

VLCを再インストールの上、再度試しても同じエラーで再生不可になります。
またIEの「アドオンの管理」での「Shockwave Flash Object」は有効になっております。

**Comment by kanreisa** [comment]
1. お使いの環境が64bitの場合は64bit版のVLCプラグインが入っているか確認してください。
2. Win 7 では再生できないかもしれませんが、前後の wui ログを貼り付けてもらえますか？

`chinachu test ffmpeg` の結果も貼り付けてください。

※Flash は使用しておりません。

**Comment by shirow-github** [comment]
A1.
OSはWin7 64bit版で、VLCは32bit版を使用しておりました。
そのためVLC 32bit版をアンインストールの上、同バージョンの64bit版に入れ替えて試したのですが
結果は変わらずダメでした。

A2.
wuiのログです。
'--------------------------------------------------
16 Apr 18:48:33 - 200 GET:/api/recorded/gr63520-2uv/preview.txt?width=640&height=360&pos=32 192.168.11.5 .NET4.0E)
16 Apr 18:48:35 - 304 GET:/page/program/watch.js 192.168.11.5 .NET4.0E)
16 Apr 18:48:35 - 304 GET:/icons/film.png 192.168.11.5 .NET4.0E)
16 Apr 18:48:41 - 200 GET:/api/recorded/gr63520-2uv/watch.xspf?ext=m2ts&c%3Av=copy&c%3Aa=copy&prefix=http%3A%2F%2F192.168.11.3%3A20772%2Fapi%2Frecorded%2Fgr63520-2uv%2F 192.168.11.5 .NET4.0E)
16 Apr 18:48:57 - STREAMING: /api/recorded/gr63520-2uv/watch.mp4?ext=mp4&c%3Av=libx264&c%3Aa=libfdk_aac&s=960x540&b%3Av=256k&b%3Aa=32k&ss=0
16 Apr 18:48:57 - 200(!500) GET:/api/recorded/gr63520-2uv/watch.mp4?ext=mp4&c%3Av=libx264&c%3Aa=libfdk_aac&s=960x540&b%3Av=256k&b%3Aa=32k&ss=0  .NET4.0E)
16 Apr 18:48:57 - ECONNRESET
'--------------------------------------------------

$ ./chinachu test ffmpeg
ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.2 (GCC)
  configuration: --prefix=/home/chinachu/chinachu/usr --enable-static --disable-shared --enable-nonfree --enable-gpl --disable-ffplay --disable-avdevice --disable-network --disable-devices --enable-libx264 --enable-libvpx --enable-libfdk-aac --enable-libvorbis --disable-debug --disable-decoders --disable-encoders --disable-demuxers --disable-muxers --disable-parsers --disable-protocols --disable-filters --enable-zlib --enable-decoder=aac --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=mpeg2video --enable-decoder=mpeg4 --enable-decoder=pcm_alaw --enable-decoder=pcm_bluray --enable-decoder=h264 --enable-encoder=aac --enable-encoder=png --enable-encoder=mjpeg --enable-encoder=libx264 --enable-encoder=libvorbis --enable-encoder=libvpx_vp8 --enable-encoder=libfdk_aac --enable-encoder=mpeg2video --enable-encoder=mpeg4 --enable-encoder=nvenc --enable-demuxer=mpegts --enable-muxer=gif --enable-muxer=mjpeg --enable-muxer=mp4 --enable-muxer=mpegts --enable-muxer=webm --enable-muxer=image2 --enable-parser=aac --enable-parser=ac3 --enable-parser=h264 --enable-parser=hevc --enable-parser=mjpeg --enable-parser=mpeg4video --enable-parser=mpegaudio --enable-parser=mpegvideo --enable-parser=opus --enable-parser=png --enable-parser=vorbis --enable-parser=vp8 --enable-protocol=pipe --enable-protocol=file --enable-filter=crop --enable-filter=hqdn3d --enable-filter=pad --enable-filter=resample --enable-filter=aresample --enable-filter=scale --enable-filter=setpts --enable-filter=settb --enable-filter=yadif --enable-filter=trim --extra-cflags='-I/home/chinachu/chinachu/usr/include --static' --extra-ldflags=-L/home/chinachu/chinachu/usr/lib
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
failed somehow

**Comment by kanreisa** [comment]
1
アドオンの管理でVLCは表示されていますか？

2
Windows 7 + IE11の環境では試してませんが、元々非対応なのかもしれません。

**Comment by shirow-github** [comment]
A1.
IEの「アドオンの管理」→「すべてのアドオン」を選択すると以下の通り表示されます。
VLC ActiveX Plugin and IE Web Plugin v2

※しかし「現在読み込まれているアドオン」には表示されないので、少し？な感じです。

A2.
普段はChrome(Blink)を使っているので実使用上は問題ないです。
お手数お掛けしました。

**Comment by noraneco** [comment]
こちらでも同様の問題が発生します。
以前にどうなっているのか少し見てみたのですが、おそらく、
https://github.com/kanreisa/Chinachu/blob/master/web/page/program/watch.js#L114
で、window.navigator.plugins['VLC Web Plugin'] をチェックしているのですが、IE ではwindow.navigator.plugins ではプラグインが取れてこないようです。このため、VLC ActiveXプラグインがインストールされていたとしても IE では常に「MPEG-2 TSコンテナの再生にはVLC Web Pluginが必要です。」が表示されるのではないかと思います。
また、上記のプラグイン判定を通すように修正しても、IE では、object には再生リストが設定されていないため、再生されません（object 要素は生成されていますが、何も設定されていないと思います）。
embed 要素の代わりに vlc 変数に object 要素を突っ込んでやればいいかとも思いましたが、ActiveX プラグインのインターフェイスは NSAPI のインターフェイスと結構ちがうようなので、簡単にはいかなそうでした。なので、勝手に IE の TS 再生は未実装というステータスなのかなぁと思っておりました。
私も Firefox を利用していますので、IE で再生できなくても不自由はしておりません。

**Comment by noraneco** [comment]
m2tsのブラウザ上の再生はサポートしなくなる方向のようです。
develop-betaではIE11でmp4の再生が安定したようです。こちらではIE11でmp4の再生ができるようになりました。確認してみてください。
