### ISSUE TITLE
VLC webplugin 再生時にシークするとシークバーの位置がずれる

### ISSUE THREAD

**Issue by noraneco** [kanreisa/Chinachu#188]
Firefox で m2ts をストリーミング再生しているときに、しばらく再生してからシークすると、再生位置は正しくシークされますが、プログレスバーの位置が後ろ方向にずれてしまいます。
webplugin で再生している場合に、シークや再生を開始した後どの程度再生しているかを保持するために定期的に vlc.currentTime の値を増加させていますが、この値をシーク時にリセットしていないため、シークすると再生していた時間分だけプログレスバーの位置がずれてしまっているようです。
とりあえず、このようにすると問題は発生しなくなりました。

https://github.com/noraneco/Chinachu/commit/1045c5ac785041dcb9bcc689f1df6ce3383c52b8

**Comment by kanreisa** [comment]
VLC Web Plugin 廃止してしまったでゲソ

**Comment by noraneco** [comment]
vlc web pluginの廃止は少し残念ですが、develop-betaではmp4の再生が安定したようですので、問題は少ないかなと思います。vlc web pluginは不安材料やトラブルの種になりそうですし。
対応検討していただきありがとうございました。
