### ISSUE TITLE
要望：m2tsストリーミング再生でインタレース解除

### ISSUE THREAD

**Issue by noraneco** [kanreisa/Chinachu#190]
ストリーミング再生でブラウザで再生させることが多いのですが、デフォルトではインタレース解除がされていません。
トランスコードしている場合は変換時にインタレース解除を行うのがよいのかと思いますが、私個人の使い方は m2ts を無変換なので、vlc.video.deinterlace.enable をコードに書き加えて対処しています。
具体的にはこのようにしています。

https://github.com/noraneco/Chinachu/commit/221e63b44b5eb722a56dc0ef2636e7c989e1b9d9

ウェブ再生時のインタレース解除の機能が実装されたらうれしいと思います。
よろしくお願いします。

**Comment by kanreisa** [comment]
無変換以外は全てデインタレースするようになりました。いかがでしょう。

**Comment by noraneco** [comment]
mp4でインタレースが解除されていることを確認しました。
ありがとうございます。
