### ISSUE TITLE
installerの8番であるlibvpxのgit先

### ISSUE THREAD

**Issue by izenizen** [kanreisa/Chinachu#191]
アドレスに変更が行われており、インストールが失敗するようになりました。

**Comment by izenizen** [comment]
1) Auto (full)            5) Node.js Modules       9) libfdk-aac
2) Auto (fast)            6) epgdump              10) libogg
3) submodule              7) libx264              11) libvorbis
4) Node.js Environment    8) libvpx               12) ffmpeg
what do you install? > 8
selected: libvpx
Installing libvpx from http://git.chromium.org/webm/libvpx.git
Cloning into '/home/chinachu/chinachu/usr/src/libvpx'...
fatal: http://git.chromium.org/webm/libvpx.git/info/refs not valid: is this a gi
t repository?
./chinachu: line 263: cd: /home/chinachu/chinachu/usr/src/libvpx: No such file o
r directory
./chinachu: line 266: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
couldn't make libvpx

**Comment by kanreisa** [comment]
b3101b3 修正しました :)
