### ISSUE TITLE
手動録画時に勝手にワンセグ録画される

### ISSUE THREAD

**Issue by hihiirogane** [kanreisa/Chinachu#196]
動作環境はUbuntu12.04 x64です。

番組表から手動で予約を行った場合、普通の予約を選択したはずなのにワンセグで録画されていました。

下記のような操作を行うと現象が再現しました。
1. webの番組表から手動にて番組を予約(ワンセグ予約ではない方)
2.data/reserves.jsonを確認。予約した番組に"1seg"のパタメータは存在せず
3.webのルール画面から「スケジューラの実行」を実行
4.data/reserves.jsonを確認。予約した番組に"1seg"のパタメータが存在

そのまま予約時間になると録画コマンドに1segがついていました。

自分はフルセグで録画をしたかったので、現在app-operator.js内の
録画コマンドを生成している所でワンセグ録画の条件分岐をコメントアウトして使用しています。

ルール設定された自動録画の方は勝手にワンセグ録画になることはないようです。

ワンセグ録画機能が追加された思ったのですが、
webの予約済画面の一覧もしくは番組詳細に録画モードがワンセグなのかフルセグなのかの表示があるとうれしいです。
現状では、webの録画中画面にて録画コマンドを確認するまでどちらで録画されるのか確認できませんので。

**Comment by kanreisa** [comment]
修正しましたのでご確認ください。

**Comment by hihiirogane** [comment]
手動予約してもワンセグ録画にならない事を確認しました。

#196と別になると思いますが手動でワンセグ予約した場合に
data/reserves.jsonを確認をすると「"1seg":true」のパラメータが付いていないようです。
個人的にはワンセグ録画をする予定はないので問題ないのですが。。。(^^;)

それでは、対応ありがとうございました。

**Comment by kanreisa** [comment]
おそらくコメントアウトされた物がそのまま残っている可能性があります。
修正を適用するために `git reset --hard` 等を実行して元に戻してください。

**Comment by hihiirogane** [comment]
"git reset --hard"を実行して再起動しましたところ、手動ワンセグ予約の挙動が元に戻りました。
お騒がせしました。

**Comment by kanreisa** [comment]
ご報告ありがとうございました！
また何かあればお気軽にどうぞ。
