### ISSUE TITLE
chinachuの開発者はどうなった？？

### ISSUE THREAD

**Issue by asagiri1651561** [kanreisa/Chinachu#212]
Web App - Unavailable https://chinachu.moe/

にアクセスすると以下が表示され

Error 403 - This web app is stopped.

The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the Administrator of this web app, please visit the Azure Portal to check why the app is stopped.

今期、リリース予定だったnew chinachuはリリースされてないし
作者は、生きてるのでしょうか？

**Comment by kanreisa** [comment]
死んでます
