### ISSUE TITLE
ループするバグ

### ISSUE THREAD

**Issue by asagiri1651561** [kanreisa/Chinachu#213]
ルールで対象説明文のみ指定し録画中のを録画中止にしたら録画済に表示され
録画済の一覧から録画ファイルと履歴を削除すると、また録画中に表示され録画が開始されてしまう。
永遠とループ状態です。

11 Sep 06:25:21 - LOCK: PT3-T1 (n=2)
11 Sep 06:25:21 - SPAWN: recpt1 --device /dev/pt3video2 --b25 --strip --sid 2064 16 - - (pid=2026)
11 Sep 06:25:21 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:25:21 - STREAM: /root/recorded/あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】 [150911-0555 GR16].m2ts
11 Sep 06:25:21 - #recpt1: using device: /dev/pt3video2 using B25... enable B25 strip pid = 2026
11 Sep 06:25:22 - #recpt1: device = /dev/pt3video2
11 Sep 06:25:22 - #recpt1: C/N = 34.831369dB
11 Sep 06:25:23 - #recpt1: bcas->init failed Cannot start b25 decoder Fall back to encrypted recording
11 Sep 06:25:23 - #recpt1: Recording...
11 Sep 06:25:23 - #recpt1: Available sid = 2064 2065 2066 2448 2199 Chosen sid = 2064 Available PMT = 0x101 0x102 0x103 0x1fc8 0x7f0
11 Sep 06:28:23 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:28:28 - #recpt1: SIGTERM received. cleaning up... Recorded 185sec
11 Sep 06:28:28 - UNLOCK: PT3-T1 (n=2)
11 Sep 06:28:28 - WRITE: /usr/local/Chinachu/data/recorded.json
11 Sep 06:28:28 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:28:28 - SPAWN: /usr/local/Chinachu/recorded-command (pid=undefined)
uncaughtException: Error: spawn /usr/local/Chinachu/recorded-command ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)
11 Sep 06:28:29 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:28:42 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:28:43 - PREPARE: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:28:43 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:28:46 - RECORD: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:28:46 - LOCK: PT3-T1 (n=2)
11 Sep 06:28:46 - SPAWN: recpt1 --device /dev/pt3video2 --b25 --strip --sid 2064 16 - - (pid=2125)
11 Sep 06:28:46 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:28:46 - STREAM: /root/recorded/あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】 [150911-0555 GR16].m2ts
11 Sep 06:28:46 - #recpt1: using device: /dev/pt3video2 using B25... enable B25 strip pid = 2125
11 Sep 06:28:47 - #recpt1: device = /dev/pt3video2
11 Sep 06:28:47 - #recpt1: C/N = 35.428241dB
11 Sep 06:28:47 - #recpt1: bcas->init failed Cannot start b25 decoder Fall back to encrypted recording
11 Sep 06:28:47 - #recpt1: Recording...
11 Sep 06:28:47 - #recpt1: Available sid = 2064 2065 2066 2448 2199 Chosen sid = 2064 Available PMT = 0x101 0x102 0x103 0x1fc8 0x7f0
11 Sep 06:28:49 - #recpt1: SIGTERM received. cleaning up...
11 Sep 06:28:49 - #recpt1: Recorded 2sec
11 Sep 06:28:49 - UNLOCK: PT3-T1 (n=2)
11 Sep 06:28:49 - WRITE: /usr/local/Chinachu/data/recorded.json
11 Sep 06:28:49 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:28:49 - SPAWN: /usr/local/Chinachu/recorded-command (pid=undefined)
uncaughtException: Error: spawn /usr/local/Chinachu/recorded-command ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)
11 Sep 06:28:50 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:28:59 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:29:00 - PREPARE: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:29:00 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:29:03 - RECORD: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:29:03 - LOCK: PT3-T1 (n=2)
11 Sep 06:29:03 - SPAWN: recpt1 --device /dev/pt3video2 --b25 --strip --sid 2064 16 - - (pid=2138)
11 Sep 06:29:03 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:29:03 - STREAM: /root/recorded/あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】 [150911-0555 GR16].m2ts
11 Sep 06:29:03 - #recpt1: using device: /dev/pt3video2 using B25... enable B25 strip pid = 2138
11 Sep 06:29:03 - #recpt1: device = /dev/pt3video2
11 Sep 06:29:03 - #recpt1: C/N = 35.847355dB
11 Sep 06:29:04 - #recpt1: bcas->init failed Cannot start b25 decoder Fall back to encrypted recording
11 Sep 06:29:04 - #recpt1: Recording...
11 Sep 06:29:04 - #recpt1: Available sid = 2064 2065 2066 2448 2199 Chosen sid = 2064 Available PMT = 0x101 0x102 0x103 0x1fc8 0x7f0
11 Sep 06:35:02 - #recpt1: SIGTERM received. cleaning up...
11 Sep 06:35:02 - #recpt1: Recorded 358sec
11 Sep 06:35:02 - UNLOCK: PT3-T1 (n=2)
11 Sep 06:35:02 - WRITE: /usr/local/Chinachu/data/recorded.json
11 Sep 06:35:02 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:35:02 - SPAWN: /usr/local/Chinachu/recorded-command (pid=undefined)
uncaughtException: Error: spawn /usr/local/Chinachu/recorded-command ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)
11 Sep 06:35:03 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:35:59 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.
11 Sep 06:36:00 - PREPARE: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:36:00 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:36:03 - RECORD: 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 06:36:03 - LOCK: PT3-T1 (n=2)
11 Sep 06:36:03 - SPAWN: recpt1 --device /dev/pt3video2 --b25 --strip --sid 2064 16 - - (pid=2362)
11 Sep 06:36:03 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:36:03 - STREAM: /root/recorded/あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】 [150911-0555 GR16].m2ts
11 Sep 06:36:03 - #recpt1: using device: /dev/pt3video2 using B25... enable B25 strip pid = 2362
11 Sep 06:36:04 - #recpt1: device = /dev/pt3video2
11 Sep 06:36:04 - #recpt1: C/N = 34.598371dB
11 Sep 06:36:04 - #recpt1: bcas->init failed Cannot start b25 decoder Fall back to encrypted recording
11 Sep 06:36:04 - #recpt1: Recording...
11 Sep 06:36:04 - #recpt1: Available sid = 2064 2065 2066 2448 2199 Chosen sid = 2064 Available PMT = 0x101 0x102 0x103 0x1fc8 0x7f0
11 Sep 06:36:57 - #recpt1: SIGTERM received. cleaning up...
11 Sep 06:36:57 - #recpt1: Recorded 53sec
11 Sep 06:36:58 - UNLOCK: PT3-T1 (n=2)
11 Sep 06:36:58 - WRITE: /usr/local/Chinachu/data/recorded.json
11 Sep 06:36:58 - WRITE: /usr/local/Chinachu/data/recording.json
11 Sep 06:36:58 - SPAWN: /usr/local/Chinachu/recorded-command (pid=undefined)
uncaughtException: Error: spawn /usr/local/Chinachu/recorded-command ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)
11 Sep 06:36:59 - READ: `/usr/local/Chinachu/data/recorded.json` is updated.

11 Sep 05:28:32 - WRITE: /usr/local/Chinachu/data/schedule.json
11 Sep 05:28:32 - RUNNING SCHEDULER.
11 Sep 05:28:32 - TUNERS: {"BS":2,"CS":2,"GR":2}
11 Sep 05:28:32 - RESERVE: gr2064-61h 2015-09-11T05:30:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 05:28:32 - RESERVE: gr2064-61i 2015-09-11T05:55:00+0900 [ＭＢＳ毎日放送] あさチャン！【鬼怒川氾濫、一夜明けて…　堤防はなぜ決壊したのか】
11 Sep 05:28:32 - RESERVE: gr2064-61n 2015-09-11T11:00:00+0900 [ＭＢＳ毎日放送] ひるおび！【鬼怒川堤防決壊①なぜ被害拡大②続く懸命の救助活動③対策は】
11 Sep 05:28:32 - RESERVE: gr2064-61p 2015-09-11T11:55:00+0900 [ＭＢＳ毎日放送] ひるおび！【鬼怒川堤防決壊①なぜ被害拡大②続く懸命の救助活動③対策は】
11 Sep 05:28:32 - MATCHES: 12
11 Sep 05:28:32 - DUPLICATES: 0
11 Sep 05:28:32 - CONFLICTS: 0
11 Sep 05:28:32 - SKIPS: 2
11 Sep 05:28:32 - RESERVES: 10
11 Sep 05:28:32 - WRITE: /usr/local/Chinachu/data/reserves.json

**Comment by kanreisa** [comment]
仕様です。履歴を削除すると録画中止したことも忘れるからです。
Air では仕様が変わるのでこの問題は起きません。
