### ISSUE TITLE
geoipのlookupに失敗したときの処理について

### ISSUE THREAD

**Issue by kounoike** [kanreisa/Chinachu#216]
別件でapp-wui.jsを眺めていて気になったのですが、geoip.lookup(remoteAddress)がnullを返すとアクセスを許可していませんか？

geoip-liteを見た感じだと、geoip.lookupは

1. IPv4の範囲外
2. プライベートIP
3. データファイルから検索に失敗した場合

の3つの場合にnullが返ってくるように思います。
このうちの3番目の場合にアクセスを許可してはまずいのではないでしょうか。

一方で、2番目の場合にはアクセスを許可しないといけないと思うので、一筋縄じゃいかないと思ってPRでなくIssueとさせていただきました。

**Comment by kanreisa** [comment]
patch-welcome ですが、直近では直す予定はないのでクローズします。

**Comment by kounoike** [comment]
モジュールを色々調べたところ、[ipcheck](https://www.npmjs.com/package/ipcheck) が一番使いやすかったですね。
IPv4環境でしか試せていないですが。
