### ISSUE TITLE
chinachu installer でgitのmasterブランチを取って来てると互換性に問題があったときにトラブルが起こるかも

### ISSUE THREAD

**Issue by kounoike** [kanreisa/Chinachu#227]
chinachu installerの中で、git clone --branch=master しているものがいくつかあります。

* [epgdump](https://github.com/stz2012/epgdump/)
* [libx264](https://git.videolan.org/?p=x264.git;a=summary)
* [libvpx](https://chromium.googlesource.com/webm/libvpx)
* [libfdk-aac](https://github.com/mstorsjo/fdk-aac)

で各リポジトリのmasterブランチを取得しているので、何か大きな変化があったときにトラブルになるのではないでしょうか。
epgdumpあたりがコマンドラインや出力形式変わるような変更が入ってしまうと影響が大きいのではないでしょうか。

例えばlibvpxはtag切ってあるのでそれを参照するとか、libfdk-aacはバージョン付きのリリースがあるのでそれを取得するとか。
libx264は[daily tarball](ftp://ftp.videolan.org/pub/videolan/x264/snapshots/)のどれかに固定するとか？

epgdumpはタグもブランチも無いので、どうしたものか・・・
形式が変わって大変だとは思いますが、思い切って[Piro77氏版](https://github.com/Piro77/epgdump)に移行してしまうとか？

**Comment by kanreisa** [comment]
48afd7fa4d4c1415db6bba68c185eca9a5801a50 で修正されました。 epgdump はこのリリースでは現状維持としましょう
