### ISSUE TITLE
debianでの必要なパッケージについて

### ISSUE THREAD

**Issue by kounoike** [kanreisa/Chinachu#233]
https://github.com/kanreisa/Chinachu/wiki/Installation では以下のようになってます。

```
sudo apt-get install build-essential curl git-core libssl-dev yasm libtool autoconf libboost-all-dev
```

このうち、libboost-all-devが依存関係多すぎて、具体的に個別に指定したいと思ってchinachu installerで入れるものを調べていたのですが、何がlibboostに依存するのか見つけられませんでした。

そこで思い切ってlibboost-all-devを入れない状態で./chinachu intaller 1してみたのですが、特にエラーなく終了しているように見えます（警告で出てるのかもしれませんが）。

出来れば、「～のビルド（実行）にlibboostの～が必要」みたいな情報があると、libboostの絞込みが行えて、ビルドが楽になります。
（Dockerでの実行を画策しているので、何度もlibboost関連のパッケージをインストールしていると時間がかかる＆イメージが大きくなるので・・・）

**Comment by tdenc** [comment]
libboostはrecfsusb2nのビルドに必要なので書いてあるのだと思われますが，Chinachu自体に必要なわけではないのでWikiを編集してlibboost-all-devを削除しました。
不要であることはこちらでも念の為にテストしてあります。
