### ISSUE TITLE
Node.js Environmentのインストールに失敗する

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#234]
現在のmaster最新版のchinachuでインストールを試した所、
インストールメッセージには「done.」と表示されるが正常にインストール出来ていませんでした。

'-------------------------------------------------
what do you install? > 4
selected: Node.js Environment
Installing Node using Nave...
--2015-10-04 22:30:29--  https://github.com/isaacs/nave/archive/master.tar.gz
github.com をDNSに問いあわせています... 192.30.252.129
github.com|192.30.252.129|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 Found
場所: https://codeload.github.com/isaacs/nave/tar.gz/master [続く]
--2015-10-04 22:30:30--  https://codeload.github.com/isaacs/nave/tar.gz/master
codeload.github.com をDNSに問いあわせています... 192.30.252.147
codeload.github.com|192.30.252.147|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 7676 (7.5K) [application/x-gzip]
`STDOUT' に保存中

-                               100%[========================================================>]   7.50K  --.-KB/s 時間 0.007s 

2015-10-04 22:30:31 (1.09 MB/s) - stdout へ出力完了 [7676/7676]

nave-master/nave.sh
ディレクトリを削除しました: `/home/chinachu/chinachu-test/.nave/nave-master'

curl: (22) The requested URL returned error: 404 Not Found
######################################################################## 100.0%
installed from binary
`/home/chinachu/chinachu-test/.nave/node' -> `/home/chinachu/chinachu-test/.nave/installed/4.0.0/bin/node'
`/home/chinachu/chinachu-test/.nave/npm' -> `/home/chinachu/chinachu-test/.nave/installed/4.0.0/bin/npm'
done.
'-------------------------------------------------

$ ls -l .nave/
合計 16
-rwxr-xr-x 1 chinachu chinachu 16124 10月  1 08:28 nave.sh*
lrwxrwxrwx 1 chinachu chinachu    59 10月  4 22:30 node -> /home/chinachu/chinachu-test/.nave/installed/4.0.0/bin/node
lrwxrwxrwx 1 chinachu chinachu    58 10月  4 22:30 npm -> /home/chinachu/chinachu-test/.nave/installed/4.0.0/bin/npm

.nave/installedが無いようです。
実際は、~/.nave内にあるようです。

$ ls -l ~/.nave/
合計 8
drwxr-xr-x 3 chinachu chinachu 4096 10月  4 22:30 installed/
drwxr-xr-x 2 chinachu chinachu 4096 10月  4 22:30 src/

新しいmasterブランチの、nave.sh v0.5.2を使用するとこのような動作をするようです。
ひとつ前のv0.5.1を使用するように修正した所、正常にインストールが完了しました。

**Comment by kounoike** [comment]
https://github.com/isaacs/nave/pull/73 で指摘されているので、naveの方でもいずれ直るでしょうが、応急処置としてはchinachuスクリプトの`chinachu_installer_node ()`を以下のようにしておかないとならないようですね。

```
chinachu_installer_node () {
  remove_dir "$NAVE_DIR"
  ensure_dir "$NAVE_DIR"
  
  echo "Installing Node using Nave..."
  wget -O - https://github.com/isaacs/nave/archive/v0.5.1.tar.gz | tar zxvf - -C $NAVE_DIR nave-0.5.1/nave.sh
  mv $NAVE_DIR/nave-0.5.1/nave.sh $NAVE_DIR/
  rm -rfv $NAVE_DIR/nave-0.5.1
  ${NAVE_DIR}/nave.sh install $NODE_VER
  rm -fv ${NAVE_DIR}/node
  ln -sv $NODE_PATH ${NAVE_DIR}/node
  ln -sv $NPM_PATH ${NAVE_DIR}/npm
  
  echo "done."
  
  return 0
}
```

**Comment by falconws** [comment]
@kounoike ありがとうございました、手元で回避出来ました。

**Comment by mzyy94** [comment]
nave側に修正するよう言ったのであちら側の修正がされ次第このIssueをCloseするようにします。

https://github.com/isaacs/nave/pull/83
