### ISSUE TITLE
ffmpeg v2.6.1インストール時、libvpx関連のビルドに失敗する

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#243]
現在、chinachuのmasterブランチにて
ffmpegインストール時に以下のようなエラーが発生します。

'------------------------------------------------------
CC      libavcodec/libfdk-aacenc.o
CC      libavcodec/libvorbisenc.o
CC      libavcodec/libvpxenc.o
CC      libavcodec/libx264.o
libavcodec/libvpxenc.c:105:6: エラー: ‘VP8E_UPD_ENTROPY’ がここでは宣言されていません (関数内ではない)
     [VP8E_UPD_ENTROPY]           = "VP8E_UPD_ENTROPY",
      ^
libavcodec/libvpxenc.c:105:5: エラー: array index in initializer not of integer type
     [VP8E_UPD_ENTROPY]           = "VP8E_UPD_ENTROPY",
     ^
libavcodec/libvpxenc.c:105:5: エラー: (‘ctlidstr’ 用の初期化付近)
libavcodec/libvpxenc.c:106:6: エラー: ‘VP8E_UPD_REFERENCE’ がここでは宣言されていません (関数内ではない)
     [VP8E_UPD_REFERENCE]         = "VP8E_UPD_REFERENCE",
      ^
libavcodec/libvpxenc.c:106:5: エラー: array index in initializer not of integer type
     [VP8E_UPD_REFERENCE]         = "VP8E_UPD_REFERENCE",
     ^
libavcodec/libvpxenc.c:106:5: エラー: (‘ctlidstr’ 用の初期化付近)
libavcodec/libvpxenc.c:107:6: エラー: ‘VP8E_USE_REFERENCE’ がここでは宣言されていません (関数内ではない)
     [VP8E_USE_REFERENCE]         = "VP8E_USE_REFERENCE",
      ^
libavcodec/libvpxenc.c:107:5: エラー: array index in initializer not of integer type
     [VP8E_USE_REFERENCE]         = "VP8E_USE_REFERENCE",
     ^
libavcodec/libvpxenc.c:107:5: エラー: (‘ctlidstr’ 用の初期化付近)
make: *** [libavcodec/libvpxenc.o] エラー 1
make: *** 未完了のジョブを待っています....
couldn't make ffmpeg
'------------------------------------------------------

原因を調査した所、libvpxのmasterブランチに加えられた修正が原因のようです。

Merge "vp8cx: remove deprecated reference/entropy controls"
https://chromium.googlesource.com/webm/libvpx/+/849e54cedd5efbd0841b32a757cecca9b921e153

またlibvpxの修正に合わせて、ffmpegのmasterブランチでも修正が行われているようです。

libvpxenc: remove some unused ctrl id mappings
https://github.com/FFmpeg/FFmpeg/commit/6540fe04a3f9a11ba7084a49b3ee5fa2fc5b32ab

今回の対処としては、上記修正が加えられたffmpegがリリースされるのを待つか、
libvpxをmasterでは無く、v1.4.0を利用すればffmpeg v2.6.1でも問題なく使用出来ます。

**Comment by kounoike** [comment]
具体的にはchinachuスクリプトの`chinachu_installer_libvpx ()`内の`git clone --branch=master`を`git clone --branch=v1.4.0`にすればとりあえずの対処になるということですね。

ところで、libvpxだけ--depth=1が付いていないのは理由があるのでしょうか？
特に理由が無ければ付けておいた方が良いように思います。

**Comment by tdenc** [comment]
#250 がdevel-betaブランチにマージされましたので閉じます。
