### ISSUE TITLE
予約に失敗しました (500)

### ISSUE THREAD

**Issue by ikimono40** [kanreisa/Chinachu#245]
環境はUbuntu 14.04 + PT3です。

手動予約を実行すると"予約に失敗しました (500)"というメッセージが表示されて予約ができません。
また、ルールの作成には成功するのですが、作成したルールで番組が予約されません。

Operatorのログには以下のエラーメッセージが残っていました。

WARN: `/home/chinachu/chinachu/data/reserves.json` is invalid. (SyntaxError: Unexpected end of input)

**Comment by kounoike** [comment]
メッセージ通りreserves.jsonが壊れてるのでは？

**Comment by ikimono40** [comment]
ご返信ありがとうございます。
reserves.jsonを修復する手段としては./chinachu installerによる再インストールではダメなのでしょうか？
./chinachu installerコマンドは何回か試してみたのですが、やはり予約ができませんでした。

**Comment by kanreisa** [comment]
echo "[]" > /home/chinachu/chinachu/data/reserves.json

**Comment by ikimono40** [comment]
ご返信ありがとうございます。
echo "[]" > /home/chinachu/chinachu/data/reserves.jsonを実行してみましたが、残念ながらエラーは改善しませんでした。
別件でatコマンドやcrontabコマンドがうまく動作しないことに気づいたのですが、それがchinachuの動作に影響を与えているということは、仕様上あり得るのでしょうか？

**Comment by kanreisa** [comment]
at や crontab は使いませんがその Linux どこか壊れてるんじゃないですか

**Comment by ikimono40** [comment]
その可能性も考慮して、一度Linuxを再インストールしてみることにします。

**Comment by kanreisa** [comment]
Ubuntuであればサーバー用のdistがあるのでそれを使ってください。

**Comment by ikimono40** [comment]
了解しました。Ubuntu Server 14.04にします。
