### ISSUE TITLE
preview.txtでpngが取得できない

### ISSUE THREAD

**Issue by sudosan** [kanreisa/Chinachu#251]
`/api/recorded/:programId/preview.txt?type=png`  
を取得してもjpegで帰ってくる  
たぶんここの条件分岐がガバガバ  
https://github.com/kanreisa/Chinachu/blob/master/api/script-recorded-program-preview.vm.js#L39

**Comment by kanreisa** [comment]
ここは確かそういう仕様です。かなり昔にIEか何か用に用意した機能なので、
そのうち消える予定です。
何に使いたい感じ？

**Comment by sudosan** [comment]
自分の環境ではマシンパワーに少し余裕があり、WebUIの背景がJPEGで且つ低解像度ですこし見栄えが悪いので、PNG且つHDにし用途思ったのですが、txtではPNGで取得できずWikiの仕様とは違うなぁと思いこのissueを立てた次第です

**Comment by kanreisa** [comment]
wiki を修正しました。
