### ISSUE TITLE
スケジューラーが失敗しました (500)

### ISSUE THREAD

**Issue by kissy4286** [kanreisa/Chinachu#252]
スケジューラーが失敗しました (500)
と表示されスケジューラーが動作しないようになってしまいました。
何が原因なのでしょうか？？

**Comment by tdenc** [comment]
後ろで自動スケジューラが動いているときに手動スケジューラを動かしたのではないでしょうか？
システムログのSchedulerの項目を見て，スケジューラが動いていないことを確認してから手動で実行してみてください。
