### ISSUE TITLE
[要望] logのディレクトリをconfig.jsonで指定できるようにして頂きたい。

### ISSUE THREAD

**Issue by epgdatacapbon** [kanreisa/Chinachu#254]
Raspberry Piで、主にlogをRAMディスクに書き出したいため。

**Comment by epgdatacapbon** [comment]
主にlogをRAMディスクに書き出したいため。

**Comment by kanreisa** [comment]
シンボリックリンクを使うか、logディレクトリを直接マウントする方法でいかがですか。
ちなみに Air では次の場所に変更される予定です: `/usr/local/var/log/chinachu/`

**Comment by epgdatacapbon** [comment]
シンボリックリンクで運用しようとしたのですが、起動時のinitスクリプト実行のタイミングによってうまくいかない場合があります。systemctl statusで確認したところ、chinachuのdaemonが起動直後に終了してしまうようです。
