### ISSUE TITLE
H264がリンク切れです

### ISSUE THREAD

**Issue by hayashi46475** [kanreisa/Chinachu#257]
./chinachu installer
Chinachu Installer Menu:
[!] These are installed under all /usr/local/Chinachu/...
[!] Recommend the Auto installation.
1) Auto (full)            5) Node.js Modules       9) libfdk-aac
2) Auto (fast)            6) epgdump              10) libogg
3) submodule              7) libx264              11) libvorbis
4) Node.js Environment    8) libvpx               12) ffmpeg
what do you install? > 7
selected: libx264
Installing libx264 from git://git.videolan.org/x264.git
Cloning into '/usr/local/Chinachu/usr/src/libx264'...
fatal: repository 'https://git.videolan.org/x264.git/' not found
./chinachu: 231 行: cd: /usr/local/Chinachu/usr/src/libx264: そのようなファイルやディレクトリはありません
./chinachu: 行 234: ./configure: そのようなファイルやディレクトリはありません
make: *** ターゲットが指定されておらず, makefile も見つかりません.  中止.
couldn't make libx264

H.264 がインストール出来ないです（泣

**Comment by kanreisa** [comment]
それは大変

**Comment by kanreisa** [comment]
@hayashi46475 どないですか？

**Comment by tdenc** [comment]
URL変更だと思って#258を出しましたが，どうやらサーバの一時的な問題だったようなので取り下げました。
念の為に手元でまっさらな状態で./chinachu installerを走らせてみましたが，libx264をインストールできるようになっているのを確認しています。

**Comment by kanreisa** [comment]
今しがた別の修正をしました。

**Comment by tdenc** [comment]
@kanreisa :+1:

**Comment by hayashi46475** [comment]
訂正ありがとうございました。

./chinachu unlock
このコマンドも無くなってしまったのでしょうか？？

**Comment by kanreisa** [comment]
意味がなく危険なコマンドとなってしまいましたので、削除しました。
