### ISSUE TITLE
./chinachu service operator execute で　行 468: node: コマンドが見つかりません

### ISSUE THREAD

**Issue by ehatovcat** [kanreisa/Chinachu#260]
よろしくお願いします。
タイトルのエラーが出ます。

uname -a
Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ls /dev/pt1*
/dev/pt1video0  /dev/pt1video1  /dev/pt1video2  /dev/pt1video3

<現況>
PT1(一枚指し)　PT1とカードリーダ(NTT)ドライバ導入動作済み arib25導入済み
pt1recコマンドでの地上とBS(LNB電源ON済)の視聴&録画TS保存試験まではできている状態です。
(LAN内でストリーミング゛でも視聴可)

<経緯・疑問>
WIndowsxpと8.1(64)でのTVRock+TvTest(64)の録画視聴環境構築経験はあります(PT二枚差し)。
epgrec UNAの導入に数度失敗しており、その同環境でのchinachu導入という状況です。 
Linuxは久々のインストールで、コマンドもコピーペーストするような初心者レベルです。

468行目というのが多分外部コマンドを呼んでいるのだと思いますが、どのソースファイルなのでしょうか。
それによって何の要素が足りないかわかるかもと思っているのですが・・。
epgrec UNA失敗でPHPとかの環境がスパゲッティーになったためにエラーが出ている可能性あるでしょうか。
諦めてまたOS再インストールからやり直しも検討に入っています。

まだなんとかなりそうであれば、ご教示ください。

**Comment by ehatovcat** [comment]
補足です。
参考にしたサイト
http://www.jifu-labo.net/2015/09/ubuntu_chinachu/
PT1のため、config.jsonのPT3部分をPT1へ書き換えています。
上記サイト内のjson構文チェックサイトのチェックではエラーは出ていません。

config.json内でPT3部分をPT1へ書き換えています。

 "tuners": [
    {
      "name"        : "PT1-S1",
      "isScrambling": false,
      "types"       : [ "BS", "CS" ],
      "command"     : "recpt1 --device /dev/pt1video0 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT1-S2",
      "isScrambling": false,
      "types"       : [ "BS", "CS" ],
      "command"     : "recpt1 --device /dev/pt1video1 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT1-T1",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recpt1 --device /dev/pt1video2 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT1-T2",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recpt1 --device /dev/pt1video3 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "FSUSB2",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recfsusb2n -b <channel> - -",
      "noEpg"       : true
    }

**Comment by tdenc** [comment]
./chinachu installerは実行しましたか？

**Comment by ehatovcat** [comment]
ありがとうございます。

はい、./chinachu installer　は Auto (full)で実行しました。
その際はエラーメッセージで止まるようなことはなく最後までdoneとokだけで完走しました
と思ったのですが、実行ログをよく見たらこんなのが埋もれていました・・。!

Installing Node Modules using NPM...
./chinachu: 行 173: npm: コマンドが見つかりません
./chinachu: 行 174: npm: コマンドが見つかりません
done.
これは・・コケてたってことですね。
npm?対象のファイル手動書き換えなどでリカバリでしょうか。

**Comment by ehatovcat** [comment]
ごめんなさい　わかったみたいです。

/home/chinachu/chinachu/.nave/nave.sh: 行 241: curl: コマンドが見つかりません

というエラーも出ていて、たしかにnave.shの241行目にはcurlという命令が使われていて、
ではcurlとは?と調べたらcurlという外部モジュールがあって、それを追加インストールしたら
chinachuインストーラが明らかに最初と違う動きをして完走し、

~/chinachu $ ./chinachu service operator execute
14 Jan 13:45:30 - MKDIR: ./recorded/
14 Jan 13:45:30 - READ: `/home/chinachu/chinachu/data/reserves.json` is updated.
14 Jan 13:45:30 - READ: `/home/chinachu/chinachu/data/recorded.json` is updated.
14 Jan 13:45:31 - SPAWN: node app-scheduler.js -f (pid=19664)
14 Jan 13:45:31 - STREAM: ./log/scheduler

と動きました!
落ち着いてログを見返すように誘導してもらったおかげです。
お手数おかけしました・・。引き続きやってみます。ありがとうございます。

**Comment by kanreisa** [comment]
ところで、
```
,
{
"name" : "FSUSB2",
"isScrambling": false,
"types" : [ "GR" ],
"command" : "recfsusb2n -b - -",
"noEpg" : true
}
```
これは不要かと思います。

**Comment by ehatovcat** [comment]
どうもですー。

調べたら、ここは他のキャプチャ機器用の記述みたいですね。
削除したいと思います。

おかげさまで、あれから受信・録画までたどりつきました。
ついに自分ような技量でもここまでやれるようになったLinux環境の進化とchinachuに感謝です。
