### ISSUE TITLE
Add IPv6 Support

### ISSUE THREAD

**Issue by nunnun** [kanreisa/Chinachu#261]
Chinachu AirのWikiを拝見したところ、IPv6はdeprecatedされておりますが、これから（いよいよ）IPv6がdeployされることや、ChinachuをNGN網内折り返しで利用したいと考えており、再度サポートしていただきたいのですがいかがでしょうか？

よろしくお願いします。

**Comment by kanreisa** [comment]
LANを越えたホストはサポートされません。
VPNかChinachu Cloudを利用する方法をおすすめしています。

**Comment by nunnun** [comment]
コメントありがとうございます。
同一L2内であればIPv6でも通信出来ると考えてよろしいでしょうか？

**Comment by kanreisa** [comment]
いいえ。当面はサポートされません。NGN網内折り返しは今後もサポートできません。

**Comment by nunnun** [comment]
@kanreisa ありがとうございます。了解しました。
