### ISSUE TITLE
USからのアクセスをブロックする必要はあるのでしょうか。

### ISSUE THREAD

**Issue by simplelife0530** [kanreisa/Chinachu#271]
ログにこんなのがでてました。

16 Apr 12:11:50 - 403 GET:/favicon.ico XXXXX "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
Non-allowed Country IP Blocked XXXXXX {"range":[1235394560,1235394687],"country":"US","region":"CA","city":"San Jose","ll":[37.2972,-121.8868],"metro":807}
Can't set headers after they are sent.

パスワードがあれば、アクセス制御できると思います。
国外で利用してはいけないというルールがあるなら、ちょっと調べてみたいとは思いますが。。。。

**Comment by kanreisa** [comment]
`config.json` を見直して頂ければと思います。ブロックの必要性については、利用者に委ねています。

**Comment by simplelife0530** [comment]
わかりました。
いろんな設定ができるんですね。
勉強になりました。
