### ISSUE TITLE
WEBアクセス時待ち時間が長くなった

### ISSUE THREAD

**Issue by RLambert142** [kanreisa/Chinachu#274]
久々にアップデートしました。
http://192.168.xxx.xx:10772/
にアクセス後、中央付近にピンク色のが円を書くように
グルグルと回って１分ぐらいすると、切断されましたと通知が出てきてからじゃないと
ダッシュボードとかが表示されません。
ちょっと遅すぎて録画状況とか確認するときに待ち時間が長すぎる気がして・・・

Windows7 SP1
GoogleChrome 50.0.2661.94 m (64-bit)

**Comment by kanreisa** [comment]
さいげんできませんでした
