### ISSUE TITLE
「録画済」が0件の時にWUIの見栄えがおかしくなる

### ISSUE THREAD

**Issue by taikoyaP** [kanreisa/Chinachu#78]
録画した後、「クリーンアップ」等で録画済が0件になると、ダッシュボードの「録画済」の文字の位置がおかしくなります。

![chinachu-ss](https://f.cloud.github.com/assets/2113819/1887645/f4bc431a-7a00-11e3-8a3b-20c5bea8b176.png)

**Comment by kanreisa** [comment]
これを修正する余力がないのでUsushioまでパスです
