### ISSUE TITLE
Recording fails immediately if recording process fails

### ISSUE THREAD

**Issue by viddypiddy** [kanreisa/Chinachu#87]
Hello,

This might not be a issue or a bug, unless "retry" functionality is already implemented. 
Is chinachu supposed to give up immediately if the tuner process fails?

I would believe that it could retry with another free tuner of the same type if it fails to avoid broken recordings.

Example
```
29 Jan 03:09:00 - PREPARE: 2014-01-29T03:10:00 [テレビ朝日] ももクロＣｈａｎ
29 Jan 03:09:00 - WRITE: /home/chinachu/chinachu/data/recording.json
29 Jan 03:09:55 - RECORD: 2014-01-29T03:10:00 [テレビ朝日] ももクロＣｈａｎ
29 Jan 03:09:55 - LOCK: PT2-T1 (n=2)
29 Jan 03:09:55 - SPAWN: recpt1 --device /dev/pt1video2 --b25 --sid 1064,epg 24 - - (pid=14327)
29 Jan 03:09:55 - WRITE: /home/chinachu/chinachu/data/recording.json
29 Jan 03:09:55 - STREAM: ./recorded/[140129-0310][GR24][PT2-T1]ももクロＣｈａｎ.m2ts
29 Jan 03:09:55 - #recpt1: using device: /dev/pt1video2 using B25... pid = 14327
29 Jan 03:09:59 - #recpt1: Cannot tune to the specified channel: /dev/pt1video2
29 Jan 03:09:59 - UNLOCK: PT2-T1 (n=2)
```

The end result is a 0 byte sized file.

In this particular case it seems the pt2 driver failed in some way (It was able to tune after a reboot), but I did lose a recording even if /dev/pt1video3 was still working and free for chinachu to use.

What do you think?

**Comment by kanreisa** [comment]
now you can use [Mirakurun and Rivarun](https://github.com/kanreisa/Chinachu/wiki/Using-Mirakurun-with-Rivarun-on-Chinachu-Beta).
